### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:4566

### ISSUE THREAD

**Issue by dfang** [localstack/serverless-localstack#102]
my case is lambda receive a s3 put event, download the csv, parsed it and save it to dynamodb

part of my serverless.yaml

```
custom:
  localstack:
    debug: true
    stages:
      # list of stages for which the plugin should be enabled
      - local
    host: http://localhost
    edgePort: 4566
    # should be false when in test stage, use real aws for CI
    # true in local stage, improve this later
    autostart: true
    lambda:
      # Enable this flag to improve performance
      mountCode: true
```

lambda handler.js

```
    let s3
    let dynamoDB
    if (process.env.IS_OFFLINE === 'true') {
        s3 = new AWS.S3({
        s3ForcePathStyle: true,
        endpoint: new AWS.Endpoint('http://localhost:4566'),
        });
        dynamoDB = new AWS.DynamoDB({
            region: 'localhost',
            endpoint: 'http://localhost:4566',
        });
    } else {
        dynamoDB = new AWS.DynamoDB();
        s3 = new AWS.S3();
    }

   // Download the file from the S3 source bucket. 
    try {
      const params = {
        Bucket: srcBucket,
        Key: srcKey
      };
      var originFile = await s3.getObject(params).promise();
    } catch (error) {
      console.log(error);
    }

    try {
      let bodyString = originFile.Body.toString()
      let parsed = await parseCSV(bodyString)
     // save to DB 
    } catch (error) {
      console.error(error)
    }
```

my e2e test

```
upload a csv to the bucket
check items count in dynamoDB table 
```

my e2e test always fail, because from docker logs I found:

```
> 2020-08-31T14:48:37.825Z	1450c500-717f-1023-ca2a-a8f7fe397e43	INFO	srcBucket is  local-5da32ac332
> 2020-08-31T14:48:37.825Z	1450c500-717f-1023-ca2a-a8f7fe397e43	INFO	srcKey is  y4l82mbv7g.csv
> 2020-08-31T14:48:38.396Z	1450c500-717f-1023-ca2a-a8f7fe397e43	INFO	Error: connect ECONNREFUSED 127.0.0.1:4566
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
>   errno: 'ECONNREFUSED',
>   code: 'NetworkingError',
>   syscall: 'connect',
>   address: '127.0.0.1',
>   port: 4566,
>   region: 'us-east-1',
>   hostname: 'localhost',
>   retryable: true,
>   time: 2020-08-31T14:48:38.394Z
> }
> 2020-08-31T14:48:38.397Z	1450c500-717f-1023-ca2a-a8f7fe397e43	INFO	undefined
> 2020-08-31T14:48:38.397Z	1450c500-717f-1023-ca2a-a8f7fe397e43	ERROR	TypeError: Cannot read property 'Body' of undefined
>     at Runtime.exports.handler (/var/task/handler.js:51:35)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

open http://127.0.0.1:4566/local-5da32ac332/y4l82mbv7g.csv in browser will download that file
and awslocal s3 ls can list files

```
$ awslocal s3 ls s3://local-5da32ac332/
2020-08-31 22:37:13        639 k6iy5qtks1.csv
2020-08-31 22:38:12        639 lnujp41wy7d.csv
2020-08-31 22:48:32        639 y4l82mbv7g.csv
```

localstack container :

```
$ docker images | grep localstack
localstack/localstack   latest              e9c00b45860c

$ docker ps | grep localstack
966c6270c80c        localstack/localstack   "docker-entrypoint.sh"   46 minutes ago      Up 46 minutes       0.0.0.0:4566-4622->4566-4622/tcp, 8080/tcp   localstack_main

```

envs from lambda in docker logs:

```
> START RequestId: 1450c500-717f-1023-ca2a-a8f7fe397e43 Version: $LATEST
> 2020-08-31T14:48:37.822Z	1450c500-717f-1023-ca2a-a8f7fe397e43	INFO	ENVIRONMENT VARIABLES
> {
>   "AWS_LAMBDA_FUNCTION_VERSION": "$LATEST",
>   "HOSTNAME": "ef6f69662225",
>   "_LAMBDA_CONTROL_SOCKET": "14",
>   "BUCKET": "5da32ac332",
>   "AWS_LAMBDA_FUNCTION_TIMEOUT": "6",
>   "LOCALSTACK_HOSTNAME": "172.17.0.2",
>   "AWS_LAMBDA_LOG_GROUP_NAME": "/aws/lambda/interview-local-hello",
>   "LAMBDA_TASK_ROOT": "/var/task",
>   "LD_LIBRARY_PATH": "/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib",
>   "AWS_LAMBDA_RUNTIME_API": "127.0.0.1:9001",
>   "AWS_LAMBDA_LOG_STREAM_NAME": "2020/08/31/[$LATEST]b922afef3307fb4caca87ff7dde30a50",
>   "_LAMBDA_SHARED_MEM_FD": "11",
>   "TOPIC": "5da32ac332",
>   "AWS_EXECUTION_ENV": "AWS_Lambda_nodejs12.x",
>   "_LAMBDA_RUNTIME_LOAD_TIME": "1530232235231",
>   "AWS_XRAY_DAEMON_ADDRESS": "169.254.79.2:2000",
>   "AWS_LAMBDA_FUNCTION_NAME": "interview-local-hello",
>   "PATH": "/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin",
>   "_LAMBDA_LOG_FD": "9",
>   "AWS_DEFAULT_REGION": "us-east-1",
>   "PWD": "/var/task",
>   "AWS_SECRET_ACCESS_KEY": "test",
>   "LAMBDA_RUNTIME_DIR": "/var/runtime",
>   "LANG": "en_US.UTF-8",
>   "NODE_PATH": "/opt/nodejs/node12/node_modules:/opt/nodejs/node_modules:/var/runtime/node_modules:/var/runtime:/var/task",
>   "AWS_REGION": "us-east-1",
>   "TZ": ":UTC",
>   "IS_OFFLINE": "true",
>   "NODE_TLS_REJECT_UNAUTHORIZED": "0",
>   "STAGE": "local",
>   "AWS_ACCESS_KEY_ID": "test",
>   "TABLE": "locations",
>   "SHLVL": "0",
>   "HOME": "/home/sbx_user1051",
>   "AWS_LAMBDA_FUNCTION_INVOKED_ARN": "arn:aws:lambda:us-east-1:000000000000:function:interview-local-hello",
>   "_AWS_XRAY_DAEMON_ADDRESS": "169.254.79.2",
>   "_AWS_XRAY_DAEMON_PORT": "2000",
>   "_X_AMZN_TRACE_ID": "Root=1-dc99d00f-c079a84d433534434534ef0d;Parent=91ed514f1e5c03b2;Sampled=1",
>   "_LAMBDA_SB_ID": "7",
>   "AWS_XRAY_CONTEXT_MISSING": "LOG_ERROR",
>   "_LAMBDA_CONSOLE_SOCKET": "16",
>   "_HANDLER": "handler.handler",
>   "DOCKER_LAMBDA_USE_STDIN": "1",
>   "AWS_LAMBDA_FUNCTION_MEMORY_SIZE": "1536"
> }
```

**Comment by dfang** [comment]
because lambda is executed in docker, use this

```
 s3 = new AWS.S3({
        s3ForcePathStyle: true,
        region: 'localhost',
        endpoint: `http://${process.env.LOCALSTACK_HOSTNAME}:4566`,
});
```

**Comment by sdasari404** [comment]
hey @dfang , were you able to resolve this? 

I have a similar issue while connecting to SQS queue and I get a connection timeout when I try to access my queue using 
```
QueueUrl: `http://${process.env.LOCALSTACK_HOSTNAME}:4566/000000000000/test-queue`
```
