### ISSUE TITLE
Unable to send a message to SQS from a lambda

### ISSUE THREAD

**Issue by sdasari404** [localstack/serverless-localstack#108]
Hi,

I have a simple lambda which should send a message to SQS when a file is added to my s3 bucket.

**Serverless.yml**
```
service: test-serverless

plugins:
  - serverless-localstack

frameworkVersion: '1'

custom:
  localstack:
    debug: true
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autostart: true
    docker:
      sudo: False

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  deploymentBucket:
    name: test-lambda-bucket
    serverSideEncryption: AES256

functions:
  onItemAdded:
    handler: src/onItemAdded.handler
    events:
      - s3:
          bucket: test-bucket-dev
          event: s3:ObjectCreated:*
```

**src/onItemAdded.js**
```
var AWS = require('aws-sdk');
var sqs = new AWS.SQS({accessKeyId:"hello", secretAccessKey: "world", region: "ap-southeast-2", apiVersion: '2012-11-05'});

module.exports.handler = async (event) =>  {
  try {
    const message = {
      bucket: event.Records[0].s3.bucket,
      object: event.Records[0].s3.object
    }
    console.log(`message: ${JSON.stringify(message)}`);
    var params = {
      MessageBody: JSON.stringify(message),
      QueueUrl: "http://localhost:4566/000000000000/test-queue",
      MessageGroupId: "default"
    };
    await sqs.sendMessage(params).promise()
      .then(data => console.log("Successfully added message to queue", data.MessageId))
      .catch(err => console.log("Error: ", err));;
  } catch (err) {
    console.log(err);
  }
}
```

**SQS queue**
```
>> SQS : ConfigQueue queue <<
{
    "QueueUrl": "http://localhost:4566/000000000000/test-queue"
}
```

When my handler tries to send a message to the Queue, I get the following error

```
-2:000000000000:function:test-serverless-local-onItemAdded result / log output:
localstack_main | null
localstack_main | > START RequestId: f93994f8-1b94-1c64-f40e-bf019f741987 Version: $LATEST
localstack_main | > 2020-09-16T05:37:03.896Z	f93994f8-1b94-1c64-f40e-bf019f741987	INFO	message: {"bucket":{"name":"test-bucket-dev","ownerIdentity":{"principalId":"A3NL1KOZZKExample"},"arn":"arn:aws:s3:::test-bucket-dev"},"object":{"key":"game_config.csv","size":427,"eTag":"\"262c53decbb6aad4976a4b311a0ca865\"","versionId":null,"sequencer":"0055AED6DCD90281E5"}}
localstack_main | > 2020-09-16T05:37:04.540Z	f93994f8-1b94-1c64-f40e-bf019f741987	INFO	Error:  Error: connect ECONNREFUSED 127.0.0.1:4566
localstack_main | >     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
localstack_main | >   errno: 'ECONNREFUSED',
localstack_main | >   code: 'NetworkingError',
localstack_main | >   syscall: 'connect',
localstack_main | >   address: '127.0.0.1',
localstack_main | >   port: 4566,
localstack_main | >   region: 'ap-southeast-2',
localstack_main | >   hostname: 'localhost',
localstack_main | >   retryable: true,
localstack_main | >   time: 2020-09-16T05:37:04.536Z
localstack_main | > }
localstack_main | > END RequestId: f93994f8-1b94-1c64-f40e-bf019f741987
localstack_main | > REPORT RequestId: f93994f8-1b94-1c64-f40e-bf019f741987	Init Duration: 383.20 ms	Duration: 651.31 ms	Billed Duration: 700 ms	Memory Size: 1536 MB	Max Memory Used: 56 MB
localstack_main | 2020-09-16T05:37:04:INFO:localstack.services.edge: Unable to find forwarding rule for host "485c8c06289c:4566", path "/", target header "", auth header "", data "b''"
```
I am however able to send a message through the CLI. 

Please let me know if there is something I've missed in my config or how I could potentially fix this issue. 

Thanks

**Comment by monty16597** [comment]
Hello @sdasari404, Thank you for reporting. It looks like you haven't specified the custom `QueueUrl` in the `params` variable and Custom `endpoint` option in the SQS client's variable. We have to provide a custom endpoint in order to connect to the localstack while using the AWS's SDK. We are providing you a sample code (pretty much the same code with little changes). You have to add your domain name of where you have the localstack running. It can be a Public IP or Private IP if you have the localstack running with exposed port or container name if you are running the localstack into the docker.

Code:
```
var AWS = require('aws-sdk');
var sqs = new AWS.SQS({endpoint:"http://10.0.2.15:4566", accessKeyId:"hello", secretAccessKey: "world", region: "us-east-1", apiVersion: '2012-11-05'});

module.exports.handler = async (event) =>  {
  try {
    const message = {
      bucket: event.Records[0].s3.bucket,
      object: event.Records[0].s3.object
    }
    console.log(`message: ${JSON.stringify(message)}`);
    var params = {
      MessageBody: JSON.stringify(message),
      QueueUrl: "http://10.0.2.15:4566/000000000000/test-queue",
      MessageGroupId: "default"
    };
    await sqs.sendMessage(params).promise()
      .then(data => console.log("Successfully added message to queue", data.MessageId))
      .catch(err => console.log("Error: ", err));;
  } catch (err) {
    console.log(err);
  }
}
```

**As you can see, I have added 10.0.2.15 IP as a domain name with 4566 port as a edge proxy**

**Comment by sdasari404** [comment]
hi @monty16597 ,

Thank you very much for looking into this. I've tried with an ip as well and get a connection timeout. 

**Updated handler**
```
var AWS = require('aws-sdk');
AWS.config.logger = console;

var sqs = new AWS.SQS({
  endpoint: `http://${process.env.LOCALSTACK_HOSTNAME}:4566`, 
  accessKeyId: "fml", secretAccessKey: "ffs", 
  region: "us-east-1", 
  apiVersion: '2012-11-05'
});

module.exports.handler = async (event) =>  {
  try {
    const message = {
      bucket: event.Records[0].s3.bucket,
      object: event.Records[0].s3.object
    }
    console.log(`message: ${JSON.stringify(message)}`);
    var params = {
      MessageBody: JSON.stringify(message),
      QueueUrl: `http://${process.env.LOCALSTACK_HOSTNAME}:4566/000000000000/test-queue`,
      MessageGroupId: "default",

    };
    await sqs.sendMessage(params).promise()
      .then(data => console.log("Successfully added message to queue", data.MessageId))
      .catch(err => console.log("Error: ", err));;
  } catch (err) {
    console.log(err);
  }
}
```
 **Error log**
```
localstack_main | START RequestId: 8d1e0dd2-9ae4-1752-4a70-66cda89ec851 Version: $LATEST
localstack_main | 2020-09-18T05:53:17.917Z      8d1e0dd2-9ae4-1752-4a70-66cda89ec851    INFO    message: {"bucket":{"name":"test-bucket-dev","ownerIdentity":{"principalId":"A3NL1KOZZKExample"},"arn":"arn:aws:s3:::test-bucket-dev"},"object":{"key":"test.csv","size":0,"eTag":"\"d41d8cd98f00b204e9800998ecf8427e\"","versionId":null,"sequencer":"0055AED6DCD90281E5"}}
localstack_main | 2020-09-18T05:55:26.689Z      8d1e0dd2-9ae4-1752-4a70-66cda89ec851    INFO    [AWS sqs undefined 128.766s 3 retries] sendMessage({      
localstack_main |   MessageBody: '{"bucket":{"name":"test-bucket-dev","ownerIdentity":{"principalId":"A3NL1KOZZKExample"},"arn":"arn:aws:s3:::test-bucket-dev"},"object":{"key":"test.csv","size":0,"eTag":"\\"d41d8cd98f00b204e9800998ecf8427e\\"","versionId":null,"sequencer":"0055AED6DCD90281E5"}}',
localstack_main |   QueueUrl: 'http://172.18.0.2:4566/000000000000/test-queue',
localstack_main |   MessageGroupId: 'default'
localstack_main | })
localstack_main | 2020-09-18T05:55:26.690Z      8d1e0dd2-9ae4-1752-4a70-66cda89ec851    INFO    Error:  Error: connect ETIMEDOUT 172.18.0.2:4566
localstack_main |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
localstack_main |   errno: 'ETIMEDOUT',
localstack_main |   code: 'NetworkingError',
localstack_main |   syscall: 'connect',
localstack_main |   address: '172.18.0.2',
localstack_main |   port: 4566,
localstack_main |   region: 'us-east-1',
localstack_main |   hostname: '172.18.0.2',
localstack_main |   retryable: true,
localstack_main |   time: 2020-09-18T05:55:26.686Z
localstack_main | }
localstack_main | END RequestId: 8d1e0dd2-9ae4-1752-4a70-66cda89ec851
localstack_main | REPORT RequestId: 8d1e0dd2-9ae4-1752-4a70-66cda89ec851        Init Duration: 294.52 ms                                                 Duration: 6000.00 ms     Billed Duration: 6000 ms        Memory Size: 1536 MB    Max Memory Used: 61 MB
localstack_main |

```

**Comment by monty16597** [comment]
@sdasari404 Thank you for pointing out those references.
The previous code I shared with you is working for me very well (tested on the localstack running on the host itself, not docker). I can see you have had the custom endpoint configured, but still lambda is not able to connect to the `sqs` service, strange!. Can you provide us the configurations of the local stack you are running or some information about how are you running the localstack ? If it is running on the docker then It will be more helpful to trace down the issue if you provide us the docker.compose file.  Thank you.

**Comment by sdasari404** [comment]
@monty16597 appreciate your help. I was able to resolve my issue as suggested [here](https://github.com/localstack/localstack/issues/2994)

 I was using docker to bring up my localstack. Adding `network_mode: bridge` to my docker-compose.yml resolved my issue and I can see the messages going through. 

Here is my docker-compose.yml with the change

```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "${EDGE_PORT-4566}:4566"
    environment:
      - DEFAULT_REGION=eu-west-1
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Thanks again for your help in resolving this issue.

**Comment by monty16597** [comment]
**Great work** @sdasari404 
I see, the localstack is being deployed using docker-compose. And docker-compose will create a new network for the same. So a bridge network allows containers connected to the same bridge network to communicate to the localstack.
**Thank you for drawing attention**. I think this resolved the issue and thats why we are closing this issue, please feel free to re-open or create a new issue.
**Thank you**
