### ISSUE TITLE
StepFunctions: Unable to parse and update resource

### ISSUE THREAD

**Issue by eugene-nn** [localstack/serverless-localstack#121]
Hello!

I'm currently experiencing an issue with step functions update config behaviour on localstack. 

my docker-compose file definition:

```version: '2.1'

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
 
serverless.yaml:
```service: flow

plugins:
  - serverless-localstack
  - serverless-step-functions

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566

provider:
  name: aws
  profile: default
  runtime: nodejs12.x
  stage: local
  region: us-east-1

stepFunctions:
  stateMachines:
    flow:
      definition:
        Comment: 'Simple flow'
        StartAt: Start
        States:
          Start:
            Type: Pass
            Next: Stop
#          Passthru:
#            Type: Pass
#            Next: Stop
          Stop:
            Type: Pass
            End: true
```

As you can see I have simple state machine consisting of two steps(just for test) and no error was registered on localstack yet.

Output of `sls deploy --stage local -v` looks like:

```Serverless: Using serverless-localstack
Serverless: Warning: Unable to find plugin named: TypeScriptPlugin
Serverless: Packaging service...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - flow-local
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Validating template...
Serverless: Skipping template validation: Unsupported in Localstack
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - flow-local
Serverless: Stack update finished...
Service Information
service: flow
stage: local
region: us-east-1
stack: flow-local
resources: 4
api keys:
  None
endpoints:
  None
functions:
  None
layers:
  None

Stack Outputs
ServerlessDeploymentBucketName: flow-local-serverlessdeploymentbucket-n67i63454co7
FlowStepFunctionsStateMachineArn: arn:aws:states:us-east-1:000000000000:stateMachine:flow-local-FlowStepFunctionsStateMachine-LXOPB7601I5A
```

Then after modifying existing state machine (removing comments on Passthru section):
```
...
stepFunctions:
  stateMachines:
    flow:
      definition:
        Comment: 'Simple flow'
        StartAt: Start
        States:
          Start:
            Type: Pass
            Next: Passthru
          Passthru:
            Type: Pass
            Next: Stop
          Stop:
            Type: Pass
            End: true
```
And after redeploy it I can see error:

```
2020-11-16T20:16:21:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and update resource "FlowStepFunctionsStateMachine": type object 'StateMachine' has no attribute 'update_from_cloudformation_json' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 295, in parse_and_update_resource
    return _parse_and_create_resource(logical_id, resource_json, resources_map, region_name, update=True)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 337, in _parse_and_create_resource
    parse_and_update_resource_orig(logical_id, resource_json_arns_fixed, resources_map, region_name)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 338, in parse_and_update_resource
    resource_class.update_from_cloudformation_json, "__isabstractmethod__"
AttributeError: type object 'StateMachine' has no attribute 'update_from_cloudformation_json'
```
And just for double check if I trigger command: 
```
aws --endpoint-url=http://localhost:4566 stepfunctions describe-state-machine --state-machine-arn $(aws --endpoint-url=http://localhost:4566 stepfunctions list-state-machines | jq -r '.stateMachines[].stateMachineArn') | jq .definition
``` 
I will see the initial state machine definition:

```
"{\n  \"Comment\": \"Simple flow\",\n  \"StartAt\": \"Start\",\n  \"States\": {\n    \"Start\": {\n      \"Type\": \"Pass\",\n      \"Next\": \"Stop\"\n    },\n    \"Stop\": {\n      \"Type\": \"Pass\",\n      \"End\": true\n    }\n  }\n}"
``` 

prettified version:
```
{
  Comment: 'Simple flow',
  StartAt: 'Start',
  States: {
    Start: { Type: 'Pass', Next: 'Stop' },
    Stop: { Type: 'Pass', End: true }
  }
}
```

which is not containing latest added step - `Passthru`. 

Can you give advice on debugging the issue? Thanks

**Comment by whummer** [comment]
Thanks for reporting @eugene-nn . This should be fixed in https://github.com/localstack/localstack/commit/5a723c368b317f3dc61952709c1d07af56be332e - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks!
