### ISSUE TITLE
"cannot find the current segment/subsegment" from aws_xray_sdk even with tracing disabled

### ISSUE THREAD

**Issue by zlalvani** [localstack/serverless-localstack#122]
Hello,

I'm trying to get an existing serverless config working when running against localstack. However, I get the following warning from localstack while running `npx serverless deploy --stage local`:
```
2020-11-30T22:02:17:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: cannot find the current segment/subsegment, please make sure you have a segment open Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 107, in index
    raise result
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 581, in run
    result = self.func(self.params)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 571, in handler
    response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 341, in modify_and_forward
    listener_result = listener.forward_request(method=method,
  File "/opt/code/localstack/localstack/services/edge.py", line 81, in forward_request
    return do_forward_request(api, port, method, path, data, headers)
  File "/opt/code/localstack/localstack/services/edge.py", line 86, in do_forward_request
    result = do_forward_request_inmem(api, port, method, path, data, headers)
  File "/opt/code/localstack/localstack/services/edge.py", line 106, in do_forward_request_inmem
    response = modify_and_forward(method=method, path=path, data_bytes=data, headers=headers,
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 341, in modify_and_forward
    listener_result = listener.forward_request(method=method,
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 236, in forward_request
    tmp = client.describe_stack_events(StackName=stack_name)['StackEvents'][:1]
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/aws_xray_sdk/ext/botocore/patch.py", line 38, in _xray_traced_botocore
    return xray_recorder.record_subsegment(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/aws_xray_sdk/core/recorder.py", line 428, in record_subsegment
    subsegment = self.begin_subsegment(name, namespace)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/aws_xray_sdk/core/recorder.py", line 292, in begin_subsegment
    segment = self.current_segment()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/aws_xray_sdk/core/recorder.py", line 270, in current_segment
    entity = self.get_trace_entity()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/aws_xray_sdk/core/recorder.py", line 390, in get_trace_entity
    return self.context.get_trace_entity()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/aws_xray_sdk/core/context.py", line 99, in get_trace_entity
    return self.handle_context_missing()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/aws_xray_sdk/core/context.py", line 124, in handle_context_missing
    raise SegmentNotFoundException(MISSING_SEGMENT_MSG)
aws_xray_sdk.core.exceptions.exceptions.SegmentNotFoundException: cannot find the current segment/subsegment, please make sure you have a segment open
```
This appears correlated with the following errors `serverless` outputs: 
```
Serverless: Checking Stack update progress...
Serverless: [AWS cloudformation 500 0.399s 3 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:000000000000:stack/my-project-local/b106dc24-a9ac-4e53-a98e-baba783784b2'
})
Serverless: Recoverable error occurred (), sleeping for ~7 seconds. Try 1 of 4
Serverless: [AWS cloudformation 500 0.298s 3 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:000000000000:stack/my-project-local/b106dc24-a9ac-4e53-a98e-baba783784b2'
})
Serverless: Recoverable error occurred (), sleeping for ~7 seconds. Try 2 of 4
Serverless: [AWS cloudformation 500 0.375s 3 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:000000000000:stack/my-project-local/b106dc24-a9ac-4e53-a98e-baba783784b2'
})
Serverless: Recoverable error occurred (), sleeping for ~6 seconds. Try 3 of 4
Serverless: [AWS cloudformation 500 0.591s 3 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:000000000000:stack/my-project-local/b106dc24-a9ac-4e53-a98e-baba783784b2'
})
Serverless: Recoverable error occurred (), sleeping for ~7 seconds. Try 4 of 4
```
I assumed this had something to do with xray tracing being enabled for API Gateway, however I have it explicitly set to disabled in the `serverless.yml` for the project:
```
provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-east-1"}
  memorySize: 1024 # Overwrite the default memory size. Default is 1024
  timeout: 30 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds
  tracing:
    lambda: false
    apiGateway: false
  tags:
    service: ${self:service}
    env: ${self:provider.stage}
    deployment:ci: ${env:CI, "false"}
    deployment:source: ${env:CIRCLE_TAG, '${env:CIRCLE_BRANCH, 'dev'}'}
    deployment:commit: ${env:CIRCLE_SHA1, 'dev'}
  environment: ${file(./serverless/provider/environment.yml)}
  iamRoleStatements:
    - ${file(./serverless/provider/roles/invoke_lambda.yml)}
```
The docker-compose file I'm using to start localstack is here:
```
version: "3"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: my-project-local-localstack
    hostname: my-project-localstack
    ports:
      - "4566:4566"
      - "8080:8080"
    environment:
      - SERVICES=sqs,kinesis,dynamodb,ssm,cloudformation,s3,sts,logs,iam,apigateway,lambda,events
      - PORT_WEB_UI=8080
      - HOSTNAME_EXTERNAL=my-project-local-localstack
```

Here is the output of `npm list | grep -i serverless`
```
├─┬ serverless@1.83.2
│ ├─┬ @serverless/cli@1.5.2
│ │ ├─┬ @serverless/core@1.1.2
│ │ ├─┬ @serverless/template@1.1.4
│ │ │ ├─┬ @serverless/component-metrics@1.0.8
│ │ │ ├── @serverless/core@1.1.2 deduped
│ │ ├── @serverless/utils@1.2.0 deduped
│ ├─┬ @serverless/components@2.34.9
│ │ ├── @serverless/inquirer@1.1.2 deduped
│ │ ├── @serverless/platform-client@1.1.10 deduped
│ │ ├─┬ @serverless/platform-client-china@1.1.0
│ │ │ ├─┬ @serverless/utils-china@0.1.28
│ │ ├── @serverless/platform-sdk@2.3.2 deduped
│ │ ├── @serverless/utils@1.2.0 deduped
│ ├─┬ @serverless/enterprise-plugin@3.8.4
│ │ ├─┬ @serverless/event-mocks@1.1.1
│ │ ├─┬ @serverless/platform-client@1.1.10
│ │ ├─┬ @serverless/platform-sdk@2.3.2
│ ├─┬ @serverless/inquirer@1.1.2
│ ├─┬ @serverless/utils@1.2.0
├─┬ serverless-localstack@0.4.28
├─┬ serverless-offline@6.8.0
├── serverless-plugin-datadog@0.14.0
├─┬ serverless-plugin-select@2.0.0-rc.1
├─┬ serverless-plugin-warmup@4.9.0
├─┬ serverless-prune-plugin@1.4.3
└─┬ serverless-python-requirements@5.1.0
```

**Comment by zlalvani** [comment]
I did some further debugging and realized that this issue is caused by invoking `patch_all` from `aws_xray_sdk.core` at the module level inside of my lambda definition module.
