### ISSUE TITLE
Unexpected Lambda/ApiGateway behavior

### ISSUE THREAD

**Issue by esteveslima** [localstack/serverless-localstack#123]
Hi, 

I'm trying to setup a local testing environment with localstack and docker.
The problem is that the deployed lambda functions keep returning a empty object "{}". 
When I try to access some endpoint provided by serverless framework after deployment(like http://localhost:4566/restapis/z09nbwlif6/local/_user_request_/getExample) this is the returned message from localstack container:
## Error Message:

**localstack_1**            | 2020-12-07T20:48:40:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: docker run -i  -v "/tmp/localstack/zipfile.4d25180b":/var/task -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e EDGE_PORT="$EDGE_PORT" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY" -e NODE_TLS_REJECT_UNAUTHORIZED="$NODE_TLS_REJECT_UNAUTHORIZED"   --rm "lambci/lambda:nodejs12.x" "handler.hello"

**localstack_1**            | 2020-12-07T20:48:41:INFO:localstack.services.edge: Unable to find forwarding rule for host "7be5f2546244:4566", path "GET /", target header "", auth header "", data "b''"

_______________________________________________________________________________________________

## docker-compose.yml

	version: '3.8'
	services:
	  serverless-container
	    build:
	      context: .
	      dockerfile: Dockerfile
	    volumes:
	      - ./:/serverless-container
	    environment: 
	      - NODE_TLS_REJECT_UNAUTHORIZED=0
	    working_dir: /serverless-container
	    restart: "no"
	    depends_on:
	      - localstack

	  localstack
	    image: localstack/localstack
	    #network_mode: bridge
	    expose:
	      - "4566"
	    ports:
	      - "4566:4566"
	      - "4571:4571"
	      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
	    environment:
	      - SERVICES=${SERVICES- }
	      - DEBUG=${DEBUG- }
	      - DATA_DIR=${DATA_DIR- }
	      - PORT_WEB_UI=${PORT_WEB_UI- }
	      - LAMBDA_EXECUTOR=docker
	      - LAMBDA_REMOTE_DOCKER=false
	      #- LAMBDA_DOCKER_NETWORK=bridge
	      - DOCKER_CMD=docker
	      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
	      - DOCKER_HOST=unix:///var/run/docker.sock      
	    volumes:
	      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
	      - "/var/run/docker.sock:/var/run/docker.sock"

## serverless.yml

	service: aws-nodejs

	provider:
	  name: aws
	  runtime: nodejs12.x
	  stage: local
	  region: us-east-1

	plugins:
	  - serverless-webpack
	  - serverless-localstack

	package:
	  individually: true

	custom:
	  localstack:
	    debug: true
	    stages: [local]
	    edgePort: 4566
	    host: 'localstack'
	    autostart: false
	    docker:
	      sudo: true
	  webpack:                                        
	    webpackConfig: './webpack.config.js'

	functions:
	  hello:
	    handler: handler.hello
	    events:
	      - http:
		  method: GET              
		  path: /getExample

## handler.js

	module.exports.hello = (event) => {
	  console.log('SOME LOG');
	  return {
	    statusCode: 200,
	    body: JSON.stringify({message: 'hi', event})
	  }
	};

_______________________________________________________________________________________________

I've been searching for something in the localstack container with aws cli and trying a lot of possible solutions, but nothing worked.
## Am I missing something?

Thank you!

**Comment by whummer** [comment]
Thanks for reporting @esteveslima . Can you please refer to the Node.js Lambda programming model here: https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html#nodejs-handler-sync .

Seems like there is a difference between sync and async handlers - looks like non-async handlers require you to use the `callback` which gets passed as the third parameter to your handler function (this is also what we're using our integration tests). Hope that helps - please let us know if the problem persists. Thanks

**Comment by esteveslima** [comment]
Thanks for your reply @whummer . 
Unfortunately nothing I've been trying is working, also the deployment is no longer showing the endpoints after pulling the latest localstack image from dockerhub. 
Is there any working example for this situation?

Thanks in advance.

**Comment by mgagliardo** [comment]
Hey @esteveslima could you please hand me over the Dockerfile you are using? Or is it just a plain `FROM node:lts`? I am trying to reproduce this. Thanks!

**Comment by esteveslima** [comment]
Hi @mgagliardo , I have a simple dockerfile as follows:

    FROM node:12-alpine
      
    RUN apk add --no-cache curl && \
        apk add --no-cache bash && \
        apk add --no-cache nano && \
        npm install -g serverless
    
    EXPOSE 3000
    
    CMD tail -F foo

Also in docker-compose:

     localstack
        ...
        network_mode: bridge
        ...
        environment:
          ...
          - LAMBDA_DOCKER_NETWORK=bridge
         ...

**Comment by mgagliardo** [comment]
Hello @esteveslima, I have not been able to reproduce your issue but I can show you what I did to make it work, you can see the files I've used to reproduce this [in this gist](https://gist.github.com/mgagliardo/48739fd8709ce95d07cc4146e903607f). You will see some of them are simplified, i.e. I took out the dockerfile of the compose as it is not needed for testing (you can just use the serverless framework for this) as well as the `serverless.yml` I have taken out the webpack dependency (I am not very fond into webpack but it does not change the equation).

On the other hand, commands:

```
# Bring up localstack
$ docker-compose up

# Bring up serverless
$ NODE_TLS_REJECT_UNAUTHORIZED=0 serverless create --template aws-nodejs --path aws-nodejs
$ NODE_TLS_REJECT_UNAUTHORIZED=0 serverless deploy --stage local
```

This brings up the lambda function correctly, and you can also see in the compose I enabled `DEBUG=1` for further debugging and I also brought up the `SERVICES=lambda,s3,cloudformation,sts,apigateway,iam,route53` needed.

Now testing, if you miss the RestAPI ID you will see the following:
```
$ curl http://localhost:4566/restapis/wgvr40i4z9/local/_user_request_/getExample
{}

# And in localstack debug console:
localstack_1  | 2021-01-22T15:26:48:WARNING:bootstrap.py: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7fba215b8e50>(None) failed: An error occurred (404) when calling the GetResources operation: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
localstack_1  | <title>404 Not Found</title>
localstack_1  | <h1>Not Found</h1>
localstack_1  | <p>&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;<br>  &lt;ErrorResponse&gt;<br>    &lt;Errors&gt;<br>      &lt;Error&gt;<br>        &lt;Code&gt;NotFoundException&lt;/Code&gt;<br>        &lt;Message&gt;Invalid Rest API Id specified&lt;/Message&gt;<br>        <br>      &lt;/Error&gt;<br>    &lt;/Errors&gt;<br>  &lt;RequestID&gt;7a62c49f-347e-4fc4-9331-6e8eEXAMPLE&lt;/RequestID&gt;<br>&lt;/ErrorResponse&gt;</p>
localstack_1  |  Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 581, in run
localstack_1  |     result = self.func(self.params)
localstack_1  |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
localstack_1  |     return fn(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 605, in handler
localstack_1  |     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 373, in modify_and_forward
localstack_1  |     listener_result = listener.forward_request(method=method,
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 105, in forward_request
localstack_1  |     return do_forward_request(api, method, path, data, headers, port=port)
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 116, in do_forward_request
localstack_1  |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 136, in do_forward_request_inmem
localstack_1  |     response = modify_and_forward(method=method, path=path, data_bytes=data, headers=headers,
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 373, in modify_and_forward
localstack_1  |     listener_result = listener.forward_request(method=method,
localstack_1  |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 44, in forward_request
localstack_1  |     return invoke_rest_api_from_request(method, path, data, headers)
localstack_1  |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 240, in invoke_rest_api_from_request
localstack_1  |     return invoke_rest_api(api_id, stage, method, relative_path_w_query_params,
localstack_1  |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 252, in invoke_rest_api
localstack_1  |     path_map = helpers.get_rest_api_paths(rest_api_id=api_id)
localstack_1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 233, in get_rest_api_paths
localstack_1  |     resources = apigateway.get_resources(restApiId=rest_api_id, limit=100)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
localstack_1  |     return self._make_api_call(operation_name, kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
localstack_1  |     raise error_class(parsed_response, operation_name)
localstack_1  | botocore.exceptions.ClientError: An error occurred (404) when calling the GetResources operation: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
localstack_1  | <title>404 Not Found</title>
localstack_1  | <h1>Not Found</h1>
localstack_1  | <p>&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;<br>  &lt;ErrorResponse&gt;<br>    &lt;Errors&gt;<br>      &lt;Error&gt;<br>        &lt;Code&gt;NotFoundException&lt;/Code&gt;<br>        &lt;Message&gt;Invalid Rest API Id specified&lt;/Message&gt;<br>        <br>      &lt;/Error&gt;<br>    &lt;/Errors&gt;<br>  &lt;RequestID&gt;7a62c49f-347e-4fc4-9331-6e8eEXAMPLE&lt;/RequestID&gt;<br>&lt;/ErrorResponse&gt;</p>
localstack_1  | 
localstack_1  | 
localstack_1  | 2021-01-22T15:26:48:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request GET http://localhost:4566/restapis/wgvr40i4z9/local/_user_request_/getExample: An error occurred (404) when calling the GetResources operation: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
localstack_1  | <title>404 Not Found</title>
localstack_1  | <h1>Not Found</h1>
localstack_1  | <p>&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;<br>  &lt;ErrorResponse&gt;<br>    &lt;Errors&gt;<br>      &lt;Error&gt;<br>        &lt;Code&gt;NotFoundException&lt;/Code&gt;<br>        &lt;Message&gt;Invalid Rest API Id specified&lt;/Message&gt;<br>        <br>      &lt;/Error&gt;<br>    &lt;/Errors&gt;<br>  &lt;RequestID&gt;7a62c49f-347e-4fc4-9331-6e8eEXAMPLE&lt;/RequestID&gt;<br>&lt;/ErrorResponse&gt;</p>
localstack_1  |  Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 107, in index
localstack_1  |     raise result
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 581, in run
localstack_1  |     result = self.func(self.params)
localstack_1  |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
localstack_1  |     return fn(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 605, in handler
localstack_1  |     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 373, in modify_and_forward
localstack_1  |     listener_result = listener.forward_request(method=method,
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 105, in forward_request
localstack_1  |     return do_forward_request(api, method, path, data, headers, port=port)
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 116, in do_forward_request
localstack_1  |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 136, in do_forward_request_inmem
localstack_1  |     response = modify_and_forward(method=method, path=path, data_bytes=data, headers=headers,
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 373, in modify_and_forward
localstack_1  |     listener_result = listener.forward_request(method=method,
localstack_1  |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 44, in forward_request
localstack_1  |     return invoke_rest_api_from_request(method, path, data, headers)
localstack_1  |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 240, in invoke_rest_api_from_request
localstack_1  |     return invoke_rest_api(api_id, stage, method, relative_path_w_query_params,
localstack_1  |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 252, in invoke_rest_api
localstack_1  |     path_map = helpers.get_rest_api_paths(rest_api_id=api_id)
localstack_1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 233, in get_rest_api_paths
localstack_1  |     resources = apigateway.get_resources(restApiId=rest_api_id, limit=100)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
localstack_1  |     return self._make_api_call(operation_name, kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
localstack_1  |     raise error_class(parsed_response, operation_name)
localstack_1  | botocore.exceptions.ClientError: An error occurred (404) when calling the GetResources operation: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
localstack_1  | <title>404 Not Found</title>
localstack_1  | <h1>Not Found</h1>
localstack_1  | <p>&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;<br>  &lt;ErrorResponse&gt;<br>    &lt;Errors&gt;<br>      &lt;Error&gt;<br>        &lt;Code&gt;NotFoundException&lt;/Code&gt;<br>        &lt;Message&gt;Invalid Rest API Id specified&lt;/Message&gt;<br>        <br>      &lt;/Error&gt;<br>    &lt;/Errors&gt;<br>  &lt;RequestID&gt;7a62c49f-347e-4fc4-9331-6e8eEXAMPLE&lt;/RequestID&gt;<br>&lt;/ErrorResponse&gt;</p>
localstack_1  | 
```

Which makes sense as 404 is the error because you are most likely missing the RestAPI ID, if you fix that:
```
$ curl http://localhost:4566/restapis/u436q5otce/local/_user_request_/getExample
{"message":"hi","event":{"path":"/getExample","headers":{"Remote-Addr":"172.22.0.1","Host":"localhost:4566","User-Agent":"curl/7.64.0","Accept":"*/*","X-Forwarded-For":"172.22.0.1, localhost:4566, 127.0.0.1, localhost:4566","x-localstack-edge":"https://localhost:4566","Authorization":"AWS4-HMAC-SHA256 Credential=__internal_call__/20160623/us-east-1/apigateway/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=1234"},"multiValueHeaders":{"Remote-Addr":["172.22.0.1"],"Host":["localhost:4566"],"User-Agent":["curl/7.64.0"],"Accept":["*/*"],"X-Forwarded-For":["172.22.0.1, localhost:4566, 127.0.0.1, localhost:4566"],"x-localstack-edge":["https://localhost:4566"],"Authorization":["AWS4-HMAC-SHA256 Credential=__internal_call__/20160623/us-east-1/apigateway/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=1234"]},"pathParameters":{},"body":"","isBase64Encoded":false,"resource":"/restapis/u436q5otce/local/_user_request_/getExample","httpMethod":"GET","queryStringParameters":{},"multiValueQueryStringParameters":{},"requestContext":{"path":"/local/getExample","accountId":"000000000000","resourceId":"24zc1zplmf","stage":"local","identity":{"accountId":"000000000000","sourceIp":"127.0.0.1","userAgent":"curl/7.64.0"},"httpMethod":"GET","protocol":"HTTP/1.1","requestTime":"2021-01-22T15:27:03.453Z","requestTimeEpoch":1611329223453},"stageVariables":{}}}


# And on localstack's debug
localstack_1  | 2021-01-22T15:27:03:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: CONTAINER_ID="$(docker create -i   -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e EDGE_PORT="$EDGE_PORT" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY" -e NODE_TLS_REJECT_UNAUTHORIZED="$NODE_TLS_REJECT_UNAUTHORIZED"   --rm "lambci/lambda:nodejs12.x" "handler.hello")";docker cp "/tmp/localstack/zipfile.d6ba14d4/." "$CONTAINER_ID:/var/task"; docker start -ai "$CONTAINER_ID";
localstack_1  | 2021-01-22T15:27:07:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:us-east-1:000000000000:function:aws-nodejs-local-hello result / log output:
localstack_1  | {"statusCode":200,"body":"{\"message\":\"hi\",\"event\":{\"path\":\"/getExample\",\"headers\":{\"Remote-Addr\":\"172.22.0.1\",\"Host\":\"localhost:4566\",\"User-Agent\":\"curl/7.64.0\",\"Accept\":\"*/*\",\"X-Forwarded-For\":\"172.22.0.1, localhost:4566, 127.0.0.1, localhost:4566\",\"x-localstack-edge\":\"https://localhost:4566\",\"Authorization\":\"AWS4-HMAC-SHA256 Credential=__internal_call__/20160623/us-east-1/apigateway/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=1234\"},\"multiValueHeaders\":{\"Remote-Addr\":[\"172.22.0.1\"],\"Host\":[\"localhost:4566\"],\"User-Agent\":[\"curl/7.64.0\"],\"Accept\":[\"*/*\"],\"X-Forwarded-For\":[\"172.22.0.1, localhost:4566, 127.0.0.1, localhost:4566\"],\"x-localstack-edge\":[\"https://localhost:4566\"],\"Authorization\":[\"AWS4-HMAC-SHA256 Credential=__internal_call__/20160623/us-east-1/apigateway/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=1234\"]},\"pathParameters\":{},\"body\":\"\",\"isBase64Encoded\":false,\"resource\":\"/restapis/u436q5otce/local/_user_request_/getExample\",\"httpMethod\":\"GET\",\"queryStringParameters\":{},\"multiValueQueryStringParameters\":{},\"requestContext\":{\"path\":\"/local/getExample\",\"accountId\":\"000000000000\",\"resourceId\":\"24zc1zplmf\",\"stage\":\"local\",\"identity\":{\"accountId\":\"000000000000\",\"sourceIp\":\"127.0.0.1\",\"userAgent\":\"curl/7.64.0\"},\"httpMethod\":\"GET\",\"protocol\":\"HTTP/1.1\",\"requestTime\":\"2021-01-22T15:27:03.453Z\",\"requestTimeEpoch\":1611329223453},\"stageVariables\":{}}}"}
localstack_1  | > START RequestId: a93d1e34-dc3c-1865-6b22-ff876288946f Version: $LATEST
localstack_1  | > 2021-01-22T15:27:06.393Z      a93d1e34-dc3c-1865-6b22-ff876288946f    INFO    Executed!!!!!
localstack_1  | > 2021-01-22T15:27:06.399Z      a93d1e34-dc3c-1865-6b22-ff876288946f    INFO    SOME LOG
localstack_1  | > END RequestId: a93d1e34-dc3c-1865-6b22-ff876288946f
localstack_1  | > REPORT RequestId: a93d1e34-dc3c-1865-6b22-ff876288946f        Init Duration: 318.99 ms        Duration: 25.41 ms      Billed Duration: 100 ms Memory Size: 1536 MB   Max Memory Used: 38 MB
```

Please let me know if you need any further help, as you can see I was not able to reproduce it and I think there might be either an issue on your files or serverless setup.

**Comment by mgagliardo** [comment]
Please also remember to `docker pull localstack/localstatck:latest` before running this so as to make sure you are pulling the latest available image.
