### ISSUE TITLE
StepFunctions Outputs missing

### ISSUE THREAD

**Issue by AdamJHall** [localstack/serverless-localstack#131]
Hi,

I think I have found an issue introduced in 0.12.3 or above of localstack as using the 0.12.2 docker image seems to work.

Symptom:
When running `serverless invoke stepf --name helloWorld --log --profile localstack --stage dev` I receive the following error:
 
When using 0.12.4 and above:
```
  Serverless Error ---------------------------------------
 
  ServerlessError: "helloWorld" stateMachine does not exists.
      at /<redacted>/local-stack-template/node_modules/serverless-step-functions/lib/invoke/invoke.js:30:19
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.15.1
     Framework Version:         2.23.0
     Plugin Version:            4.4.3
     SDK Version:               2.3.2
     Components Version:        3.6.2

``` 

When using 0.12.3:
```
  Serverless Error ---------------------------------------
 
  ServerlessError: An error occurred: local-stack-template-dev - undefined.
      at /home/adam.hall/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:93:23
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.15.1
     Framework Version:         2.23.0
     Plugin Version:            4.4.3
     SDK Version:               2.3.2
     Components Version:        3.6.2
``` 

docker-compose.yml:
```
version: "3.7"
services:
  localstack:
    image: localstack/localstack:0.12.4
    networks:
      - localstack-net
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=serverless,cloudformation,stepfunctions
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=true
      - LAMBDA_REMOVE_CONTAINERS=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${PWD}/.localstack
      - DEFAULT_REGION=ap-southeast-2
      - START_WEB=0
    volumes:
      - data:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"

volumes:
  data:

networks:
  localstack-net:
    external: false
    driver: bridge
    name: localstack-net
```

serverless.yml:

```
service: local-stack-template

configValidationMode: error

package:
  include:
    - src/

custom:
  esbuild:
    bundle: true
    minify: true
    target: node12
  localstack:
    debug: true
    autostart: true
    stages:
      - dev
    host: http://localhost
    edgePort: 4566
    lambda:
      mountCode: false
    docker:
      sudo: true

plugins:
  - serverless-esbuild
  - serverless-localstack
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-2'}
  memorySize: 192 #mb (default for all)
  iamRoleStatements: []

functions:
  hello:
    handler: src/hello.handler
  world:
    handler: src/world.handler

stepFunctions:
  stateMachines:
    helloWorld:
      name: helloWorld
      definition:
        StartAt: Hello
        States:
          Hello:
            Type: Task
            Resource: 
              Fn::GetAtt: [hello, Arn]
            Next: World
          World:
            Type: Task
            Resource: 
              Fn::GetAtt: [world, Arn]
            Next: Passthru
          Passthru:
            Type: Pass
            Next: Stop
          Stop:
            Type: Pass
            End: true
```

Describing the stack outputs on 0.12.4 and above show that the stack has no outputs other than the deployment s3 bucket, so when calling invoke there is no step function to execute.

**Comment by whummer** [comment]
Thanks for reporting @AdamJHall . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks!
