### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get' Error when deploying lambdas via serverless-localstack

### ISSUE THREAD

**Issue by adrtorre** [localstack/serverless-localstack#175]
```
2022-01-20T05:14:29.300:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "CFN_STACKNAME": 'str' object has no attribute 'get' Traceback (most recent call last):

aws-mocks                       |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1525, in _run
aws-mocks                       |     self.do_apply_changes_in_loop(changes, stack, stack_name)
aws-mocks                       |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1597, in do_apply_changes_in_loop
aws-mocks                       |     self.apply_change(change, stack, new_resources, stack_name=stack_name)
aws-mocks                       |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1666, in apply_change
aws-mocks                       |     result = update_resource(resource_id, new_resources, stack_name)
aws-mocks                       |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 780, in update_resource
aws-mocks                       |     result = instance.update_resource(resource, stack_name=stack_name, resources=resources)
aws-mocks                       |   File "/opt/code/localstack/localstack/services/cloudformation/models/awslambda.py", line 78, in update_resource
aws-mocks                       |     return client.update_function_configuration(**update_config_props)
aws-mocks                       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 391, in _api_call
aws-mocks                       |     return self._make_api_call(operation_name, kwargs)
aws-mocks                       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
aws-mocks                       |     http, parsed_response = self._make_request(
aws-mocks                       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 725, in _make_request
aws-mocks                       |     return self._endpoint.make_request(operation_model, request_dict)
aws-mocks                       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 104, in make_request
aws-mocks                       |     return self._send_request(request_dict, operation_model)
aws-mocks                       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 136, in _send_request
aws-mocks                       |     success_response, exception = self._get_response(
aws-mocks                       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 167, in _get_response
aws-mocks                       |     success_response, exception = self._do_get_response(
aws-mocks                       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 218, in _do_get_response
aws-mocks                       |     parsed_response = parser.parse(
aws-mocks                       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/parsers.py", line 245, in parse
aws-mocks                       |     parsed = self._do_parse(response, shape)
aws-mocks                       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/parsers.py", line 844, in _do_parse
aws-mocks                       |     self._add_modeled_parse(response, shape, final_parsed)
aws-mocks                       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/parsers.py", line 853, in _add_modeled_parse
aws-mocks                       |     self._parse_payload(response, shape, member_shapes, final_parsed)
aws-mocks                       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/parsers.py", line 894, in _parse_payload
aws-mocks                       |     body_parsed = self._parse_shape(shape, original_parsed)
aws-mocks                       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/parsers.py", line 312, in _parse_shape
aws-mocks                       |     return handler(shape, node)
aws-mocks                       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/parsers.py", line 641, in _handle_structure
aws-mocks                       |     final_parsed[member_name] = self._parse_shape(
aws-mocks                       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/parsers.py", line 312, in _parse_shape
aws-mocks                       |     return handler(shape, node)
aws-mocks                       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/parsers.py", line 949, in _handle_list
aws-mocks                       |     return super(BaseRestParser, self)._handle_list(shape, node)
aws-mocks                       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/parsers.py", line 320, in _handle_list
aws-mocks                       |     parsed.append(self._parse_shape(member_shape, item))
aws-mocks                       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/parsers.py", line 312, in _parse_shape
aws-mocks                       |     return handler(shape, node)
aws-mocks                       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/parsers.py", line 639, in _handle_structure
aws-mocks                       |     raw_value = value.get(json_name)
aws-mocks                       | AttributeError: 'str' object has no attribute 'get'
aws-mocks                       | 
```

**Comment by whummer** [comment]
Hi @adrtorre , thanks for reporting, and apologies for the long delay. This looks more like an issue in LocalStack itself, not related to the Serverless plugin. Can you help us and provide a small example configuration, so we can replicate the issue end-to-end? Also, we've made a number of enhancements in the meantime - can you please double-check if the problem persists after pulling the `latest` Docker image? Thanks!

**Comment by dhay** [comment]
I'm having the same issue with a Chalice app when I try to redeploy/update an lambda.  Upgrading to the latest version (1.1.1.dev) doesn't seem to help.  I have to completely shut down localstack and restart in order to deploy a new version of my lambda.

**Comment by whummer** [comment]
Thanks for reporting @adrtorre @dhay  - can you please share the details of your function configuration. Is your Lambda function configured with Lambda layers, by any chance? Would be great if you can share your client code / configuration, to make it easier for us to replicate the issue.. Thanks!

**Comment by whummer** [comment]
Hi again @dhay @adrtorre Closing this issue as resolved - according to our testing, this should be resolved with the `latest` version of the Docker image. Please do let us know if the problem persists.. Thanks!
