### ISSUE TITLE
CloudFormation fails with 502 on sls deploy

### ISSUE THREAD

**Issue by fredriv** [localstack/serverless-localstack#43]
I'm running into issues with 502 errors from LocalStack when running `sls deploy` on a simple Serverless project. It is failing on the CloudFormation `describeStackEvents` when checking stack create progress. Extract from log below:

```
Serverless: Checking Stack create progress...
Serverless: [AWS cloudformation 502 0.969s 3 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:000000000000:stack/hello-dev/027791cc-d634-41d4-8629-2eae7d2cd177'
})
Serverless: Recoverable error occurred (502), sleeping for 5 seconds. Try 1 of 4
```

If I run `sls deploy` again, it progresses further and deploys the function (although again failing on checking stack progress). So the CloudFormation stack seems to actually be deploying fine in LocalStack, it's just the `describeStackEvents` operation that fails.

I am running on Mac with `serverless-localstack` 0.4.19 and Serverless Framework 1.51.0.
Sample project which reproduces issue: https://github.com/fredriv/localstack-example

Output from `sls deploy`:
```
$ SLS_DEBUG=* sls deploy
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Using serverless-localstack
Serverless: Reconfiguring service apigateway to use http://localhost:4567
Serverless: Reconfiguring service cloudformation to use http://localhost:4581
Serverless: Reconfiguring service cloudwatch to use http://localhost:4582
Serverless: Reconfiguring service lambda to use http://localhost:4574
Serverless: Reconfiguring service dynamodb to use http://localhost:4569
Serverless: Reconfiguring service kinesis to use http://localhost:4568
Serverless: Reconfiguring service route53 to use http://localhost:4580
Serverless: Reconfiguring service firehose to use http://localhost:4573
Serverless: Reconfiguring service stepfunctions to use http://localhost:4585
Serverless: Reconfiguring service es to use http://localhost:4578
Serverless: Reconfiguring service s3 to use http://localhost:4572
Serverless: Reconfiguring service ses to use http://localhost:4579
Serverless: Reconfiguring service sns to use http://localhost:4575
Serverless: Reconfiguring service sqs to use http://localhost:4576
Serverless: Reconfiguring service sts to use http://localhost:4592
Serverless: Reconfiguring service iam to use http://localhost:4593
Serverless: Reconfiguring service ssm to use http://localhost:4583
Serverless: Reconfiguring service rds to use http://localhost:4594
Serverless: Reconfiguring service elasticache to use http://localhost:4598
Serverless: Reconfiguring service secretsmanager to use http://localhost:4584
Serverless: Reconfiguring service logs to use http://localhost:4586
Serverless: Reconfiguring service cloudwatchlogs to use http://localhost:4586
Serverless: Load command deploy
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: config.options_stage: undefined
Serverless: serverless.service.custom.stage: undefined
Serverless: serverless.service.provider.stage: dev
Serverless: config.stage: dev
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless:
User stats error: Request network error: FetchError: network timeout at: https://tracking.serverlessteam.com/v1/track
    at Timeout._onTimeout (/usr/local/lib/node_modules/serverless/node_modules/node-fetch/index.js:126:13)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  name: 'FetchError',
  message: 'network timeout at: https://tracking.serverlessteam.com/v1/track',
  type: 'request-timeout'
}
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 400 0.041s 0 retries] describeStacks({ StackName: 'hello-dev' })
Serverless: Creating Stack...
Serverless: [AWS cloudformation 200 0.07s 0 retries] createStack({
  StackName: 'hello-dev',
  OnFailure: 'DELETE',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateBody: '{"AWSTemplateFormatVersion":"2010-09-09","Description":"The AWS CloudFormation template for this Serverless application","Resources":{"ServerlessDeploymentBucket":{"Type":"AWS::S3::Bucket","Properties":{"BucketEncryption":{"ServerSideEncryptionConfiguration":[{"ServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}}}},"Outputs":{"ServerlessDeploymentBucketName":{"Value":{"Ref":"ServerlessDeploymentBucket"}}}}',
  Tags: [ { Key: 'STAGE', Value: 'dev' }, [length]: 1 ]
})
Serverless: Checking Stack create progress...
Serverless: [AWS cloudformation 502 0.969s 3 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:000000000000:stack/hello-dev/027791cc-d634-41d4-8629-2eae7d2cd177'
})
Serverless: Recoverable error occurred (502), sleeping for 5 seconds. Try 1 of 4
Serverless: [AWS cloudformation 502 0.419s 3 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:000000000000:stack/hello-dev/027791cc-d634-41d4-8629-2eae7d2cd177'
})
Serverless: Recoverable error occurred (502), sleeping for 5 seconds. Try 2 of 4
Serverless: [AWS cloudformation 502 0.531s 3 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:000000000000:stack/hello-dev/027791cc-d634-41d4-8629-2eae7d2cd177'
})
Serverless: Recoverable error occurred (502), sleeping for 5 seconds. Try 3 of 4
Serverless: [AWS cloudformation 502 0.531s 3 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:000000000000:stack/hello-dev/027791cc-d634-41d4-8629-2eae7d2cd177'
})
Serverless: Recoverable error occurred (502), sleeping for 5 seconds. Try 4 of 4
Serverless: [AWS cloudformation 502 0.658s 3 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:000000000000:stack/hello-dev/027791cc-d634-41d4-8629-2eae7d2cd177'
})

  Serverless Error ---------------------------------------

  ServerlessError: 502
      at /usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:133:26
  From previous event:
      at AwsDeploy.monitorStack (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:27:12)
      at /usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:45:28
  From previous event:
      at AwsDeploy.create (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:45:8)
  From previous event:
      at AwsDeploy.<anonymous> (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:89:39)
  From previous event:
      at AwsDeploy.createStack (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:83:13)
  From previous event:
      at Object.aws:deploy:deploy:createStack [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:99:67)
      at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:464:55
  From previous event:
      at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:464:22)
      at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:484:17)
      at AwsDeploy.<anonymous> (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:93:48)
  From previous event:
      at Object.deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:89:30)
      at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:464:55
  From previous event:
      at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:464:22)
      at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:496:17)
      at /usr/local/lib/node_modules/serverless/lib/Serverless.js:116:33
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)
  From previous event:
      at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:103:74)
      at /usr/local/lib/node_modules/serverless/bin/serverless.js:60:28
      at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:136:16
      at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:57:14
      at FSReqCallback.oncomplete (fs.js:154:23)
  From previous event:
      at /usr/local/lib/node_modules/serverless/bin/serverless.js:60:6
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)
  From previous event:
      at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless.js:46:39)
      at Module._compile (internal/modules/cjs/loader.js:936:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
      at Module.load (internal/modules/cjs/loader.js:790:32)
      at Function.Module._load (internal/modules/cjs/loader.js:703:12)
      at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
      at internal/main/run_main_module.js:17:11

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.9.1
     Framework Version:         1.51.0
     Plugin Version:            1.3.10
     SDK Version:               2.1.0
```

Output from Docker:
```
$ TMPDIR=/private$TMPDIR docker-compose up
Creating network "localstack-example_default" with the default driver
Creating localstack-example_localstack_1 ... done
Attaching to localstack-example_localstack_1
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2019-09-04 22:28:00,106 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack_1  | 2019-09-04 22:28:00,109 INFO supervisord started with pid 12
localstack_1  | 2019-09-04 22:28:01,114 INFO spawned: 'dashboard' with pid 20
localstack_1  | 2019-09-04 22:28:01,118 INFO spawned: 'infra' with pid 21
localstack_1  | 2019-09-04 22:28:01,128 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack_1  | (. .venv/bin/activate; bin/localstack web)
localstack_1  | (. .venv/bin/activate; exec bin/localstack start --host)
localstack_1  | 2019-09-04 22:28:02,133 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | cannot import name 'dns_server'
localstack_1  |    WARNING: Do not use the development server in a production environment.
localstack_1  |    Use a production WSGI server instead.
localstack_1  | Starting local dev environment. CTRL-C to quit.
localstack_1  | cannot import name 'dns_server'
localstack_1  | Starting mock S3 (http port 4572)...
localstack_1  | Starting mock SNS (http port 4575)...
localstack_1  | 2019-09-04T22:28:05:INFO:localstack.multiserver: Starting multi API server process on port 51492
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | Starting mock IAM (http port 4593)...
localstack_1  | Starting mock API Gateway (http port 4567)...
localstack_1  | Starting mock DynamoDB (http port 4569)...
localstack_1  | Starting mock Lambda service (http port 4574)...
localstack_1  | Starting mock CloudFormation (http port 4581)...
localstack_1  | Starting mock CloudWatch Logs (http port 4586)...
localstack_1  | Initializing DynamoDB Local with the following configuration:
localstack_1  | Port:	4564
localstack_1  | InMemory:	true
localstack_1  | DbPath:	null
localstack_1  | SharedDb:	true
localstack_1  | shouldDelayTransientStatuses:	false
localstack_1  | CorsParams:	*
localstack_1  |
localstack_1  | 2019-09-04 22:28:06,321:API:  * Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
localstack_1  | 2019-09-04 22:28:06,321:API:  * Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
localstack_1  | 2019-09-04 22:28:06,321:API:  * Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
localstack_1  | 2019-09-04 22:28:06,330:API:  * Running on http://0.0.0.0:4557/ (Press CTRL+C to quit)
localstack_1  | 2019-09-04 22:28:06,330:API:  * Running on http://0.0.0.0:4557/ (Press CTRL+C to quit)
localstack_1  | 2019-09-04 22:28:06,330:API:  * Running on http://0.0.0.0:4557/ (Press CTRL+C to quit)
localstack_1  | 2019-09-04 22:28:06,345:API:  * Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
localstack_1  | 2019-09-04 22:28:06,345:API:  * Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
localstack_1  | 2019-09-04 22:28:06,345:API:  * Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
localstack_1  | 2019-09-04 22:28:11,545:API: 127.0.0.1 - - [04/Sep/2019 22:28:11] "GET / HTTP/1.1" 200 -
localstack_1  | Ready.
localstack_1  | 2019-09-04 22:28:18,857:API: 127.0.0.1 - - [04/Sep/2019 22:28:18] "GET /hello-dev-ServerlessDeploymentBucket-GYNYDSU53XY9?location HTTP/1.1" 404 -
localstack_1  | 2019-09-04 22:28:18,875:API: 127.0.0.1 - - [04/Sep/2019 22:28:18] "PUT /hello-dev-ServerlessDeploymentBucket-GYNYDSU53XY9 HTTP/1.1" 200 -
localstack_1  | 2019-09-04T22:28:18:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response from CloudFormation (400) POST /: b'<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Stack with id hello-dev does not exist</Message>\n  </Error>\n  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>\n</ErrorResponse>'
localstack_1  | 2019-09-04T22:28:18:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently updating stack resource hello-dev/ServerlessDeploymentBucket: None
localstack_1  | 2019-09-04T22:28:18:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource: {'Type': 'AWS::S3::Bucket', 'Properties': {'BucketEncryption': {'ServerSideEncryptionConfiguration': [{'ServerSideEncryptionByDefault': {'SSEAlgorithm': 'AES256'}}]}, 'BucketName': 'hello-dev-ServerlessDeploymentBucket-GYNYDSU53XY9'}}
localstack_1  | 2019-09-04T22:28:18:DEBUG:localstack.utils.cloudformation.template_deployer: Deploying resource type "S3::Bucket" id "ServerlessDeploymentBucket"
localstack_1  | 2019-09-04T22:28:18:DEBUG:localstack.utils.cloudformation.template_deployer: Request for creating resource type "S3::Bucket": {'Bucket': 'hello-dev-ServerlessDeploymentBucket-GYNYDSU53XY9', 'ACL': 'public-read'}
localstack_1  | 2019-09-04T22:28:24:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response from CloudFormation (500) POST /: b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
localstack_1  | 2019-09-04T22:28:24:ERROR:localstack.services.generic_proxy: Error forwarding request: Unable to parse response (syntax error: line 1, column 54), invalid XML received:
localstack_1  | b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n' Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/parsers.py", line 432, in _parse_xml_string_to_dom
localstack_1  |     parser.feed(xml_string)
localstack_1  |   File "<string>", line None
localstack_1  | xml.etree.ElementTree.ParseError: syntax error: line 1, column 54
localstack_1  |
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  |
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 234, in forward
localstack_1  |     path=path, data=data, headers=forward_headers)
localstack_1  |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 85, in forward_request
localstack_1  |     tmp = client.describe_stack_events(StackName=stack_name)['StackEvents'][:1]
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
localstack_1  |     return self._make_api_call(operation_name, kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/client.py", line 648, in _make_api_call
localstack_1  |     operation_model, request_dict, request_context)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/client.py", line 667, in _make_request
localstack_1  |     return self._endpoint.make_request(operation_model, request_dict)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request
localstack_1  |     return self._send_request(request_dict, operation_model)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/endpoint.py", line 135, in _send_request
localstack_1  |     request, operation_model, context)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/endpoint.py", line 167, in _get_response
localstack_1  |     request, operation_model)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/endpoint.py", line 218, in _do_get_response
localstack_1  |     response_dict, operation_model.output_shape)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/parsers.py", line 240, in parse
localstack_1  |     parsed = self._do_error_parse(response, shape)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/parsers.py", line 485, in _do_error_parse
localstack_1  |     root = self._parse_xml_string_to_dom(xml_contents)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/parsers.py", line 437, in _parse_xml_string_to_dom
localstack_1  |     "invalid XML received:\n%s" % (e, xml_string))
localstack_1  | botocore.parsers.ResponseParserError: Unable to parse response (syntax error: line 1, column 54), invalid XML received:
localstack_1  | b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
localstack_1  |
localstack_1  | 2019-09-04 22:28:24,202:API: Error on request:
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 303, in run_wsgi
localstack_1  |     execute(self.server.app)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 291, in execute
localstack_1  |     application_iter = app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/server.py", line 132, in __call__
localstack_1  |     return backend_app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
localstack_1  |     return self.wsgi_app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
localstack_1  |     response = self.handle_exception(e)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
localstack_1  |     reraise(exc_type, exc_value, tb)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
localstack_1  |     raise value
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
localstack_1  |     response = self.full_dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
localstack_1  |     rv = self.handle_user_exception(e)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
localstack_1  |     reraise(exc_type, exc_value, tb)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
localstack_1  |     raise value
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
localstack_1  |     rv = self.dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
localstack_1  |     return self.view_functions[rule.endpoint](**req.view_args)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/utils.py", line 140, in __call__
localstack_1  |     result = self.callback(request, request.url, {})
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/responses.py", line 168, in dispatch
localstack_1  |     return cls()._dispatch(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/responses.py", line 259, in _dispatch
localstack_1  |     return self.call_action()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/responses.py", line 340, in call_action
localstack_1  |     response = method()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/cloudformation/responses.py", line 213, in describe_stack_events
localstack_1  |     return template.render(stack=stack)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
localstack_1  |     return original_render(self, *args, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
localstack_1  |     return self.environment.handle_exception(exc_info, True)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
localstack_1  |     reraise(exc_type, exc_value, tb)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
localstack_1  |     raise value.with_traceback(tb)
localstack_1  |   File "<template>", line 4, in top-level template code
localstack_1  |
localstack_1  | jinja2.exceptions.UndefinedError: 'None' has no attribute 'events'
```

**Comment by fredriv** [comment]
I get the same errors on Linux by the way (Ubuntu 19.04, Serverless 1.51.0, Python 3.7, node 11.8.0, npm 6.11.2).

**Comment by fredriv** [comment]
Is this related to https://github.com/localstack/localstack/pull/1542 ?

**Comment by fredriv** [comment]
The sample Serverless Framework project works if I downgrade to LocalStack 0.9.6: https://github.com/fredriv/localstack-example/tree/working

So perhaps this should be reported against localstack/localstack instead?

**Comment by fredriv** [comment]
I found the issue. I've set up `region: eu-west-1` in the serverless config file, but the `describeStackEvents` call seems to hardcode `us-east-1`:
```
Recoverable error occurred (502{"StackName":"arn:aws:cloudformation:us-east-1:000000000000:stack/hello-dev/3aa04ed0-6343-407f-940f-0cbee9f755d6"}), sleeping for 5 seconds. Try 1 of 4
```

Once I changed region to `us-east-1` in `serverless.yml`, the deploy worked.

**Comment by fredriv** [comment]
Closing this, as it is handled by the `DEFAULT_REGION` config in LocalStack https://github.com/localstack/localstack#configurations

**Comment by pmyjavec** [comment]
For anyone else experiencing this, I also recommend you check the logs for localstack itself.

I was having an issue where I was passing environment variables as ints not strings and it was actually the cause of my issues.

In my case I was running localstack with docker so I used `docker logs <localstack container id> -f` to find the issue.
