### ISSUE TITLE
Getting credentials fail when profile is referenced with variables

### ISSUE THREAD

**Issue by Can-Sahin** [localstack/serverless-localstack#46]
In my `serverless.yml` my profile is set with variables like

```yml
provider:
  profile: ${self:custom.profiles.${self:custom.currentStage}, self:custom.defaultProfile}
```
But when serverless-localstack tries to get profile like

```javascript 
const tmpCreds = this.awsProvider.getCredentials();
```

it fails with exception: 
```
Error: Profile ${self:custom.profiles.${self:custom.currentStage}, self:custom.defaultProfile} does not exist
      at Object.addProfileCredentials (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:100:15)
      at AwsProvider.getCredentials (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:362:12)
      at LocalstackPlugin.reconfigureAWS (/Users/cansahin/Git/EkoTaksi-Backend/node_modules/serverless-localstack/src/index.js:339:41)
      at new LocalstackPlugin (/Users/cansahin/Git/EkoTaksi-Backend/node_modules/serverless-localstack/src/index.js:72:10)
      at PluginManager.addPlugin (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:65:28)
```

**EDIT:**
I realized that issue is fixed but not yet deployed.

**Comment by yonahforst** [comment]
I'm still having this issue using 0.4.24 and the latest from master
