### ISSUE TITLE
AWS cloudformation 503 (Service Unavailable)

### ISSUE THREAD

**Issue by bunnyUFO** [localstack/serverless-localstack#49]
My serverless.yml file worked with deploys directly to AWS, but adding the serverless-localstack plugin breaks deploys. I have tried the example service files included in here too and got same error below:

```
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 503 0.702s 3 retries] describeStacks({ StackName: 'serverless-demo-local' })
Serverless: Recoverable error occurred (Service Unavailable), sleeping for 5 seconds. Try 1 of 4
Serverless: [AWS cloudformation 503 0.916s 3 retries] describeStacks({ StackName: 'serverless-demo-local' })
Serverless: Recoverable error occurred (Service Unavailable), sleeping for 5 seconds. Try 2 of 4
Serverless: [AWS cloudformation 503 0.981s 3 retries] describeStacks({ StackName: 'serverless-demo-local' })
Serverless: Recoverable error occurred (Service Unavailable), sleeping for 5 seconds. Try 3 of 4
Serverless: [AWS cloudformation 503 1.017s 3 retries] describeStacks({ StackName: 'serverless-demo-local' })
Serverless: Recoverable error occurred (Service Unavailable), sleeping for 5 seconds. Try 4 of 4
Serverless: [AWS cloudformation 503 0.863s 3 retries] describeStacks({ StackName: 'serverless-demo-local' })
```

Current docker-compose.yml looks like this:

```
version: '2.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4593:4567-4593"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=serverless,cloudformation,iam,sts
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Localstack cloudformation seems to be running fine:

```
aws cloudformation describe-stacks --endpoint "http://localhost:4581" --region us-west-2
{
    "Stacks": []
}
```

Is anyone familiar with the error?

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-49) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @bunnyUFO . Can you please share the logs from the terminal where you're running the docker-compose stack? Debug output is enabled (`DEBUG=1`), so I'd assume that you should see some error logs in the output.

Do you think you can share a minimal, self-contained serverless config to reproduce the issue? That would help tremendously in debugging this issue. Thanks

**Comment by bunnyUFO** [comment]
@whummer Thanks for the response. I really really want to start using this plugin to set up a local environment but have not been able to.

I didn't do anything too special to reproduce.

I can reproduce it with the example code on this repo: https://github.com/localstack/serverless-localstack/tree/master/example/service
The only thing I added was docker-compose.yml file like this one:

```
version: '2.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4593:4567-4593"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=serverless,cloudformation,sns,iam,sts
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

The logs on local stack did not show anything:
```
docker-compose up
Recreating serverless_demo_localstack_1 ... done
Attaching to serverless_demo_localstack_1
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2019-10-11 00:26:07,601 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack_1  | 2019-10-11 00:26:07,603 INFO supervisord started with pid 11
localstack_1  | 2019-10-11 00:26:08,606 INFO spawned: 'dashboard' with pid 19
localstack_1  | 2019-10-11 00:26:08,607 INFO spawned: 'infra' with pid 20
localstack_1  | 2019-10-11 00:26:08,612 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack_1  | (. .venv/bin/activate; bin/localstack web)
localstack_1  | (. .venv/bin/activate; exec bin/localstack start --host)
localstack_1  | 2019-10-11 00:26:09,614 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | Starting local dev environment. CTRL-C to quit.
localstack_1  | cannot import name 'dns_server'
localstack_1  | Starting mock S3 (http port 4572)...
localstack_1  | Starting mock SNS (http port 4575)...
localstack_1  | 2019-10-11T00:26:12:INFO:localstack.multiserver: Starting multi API server process on port 51492
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | Starting mock STS (http port 4592)...
localstack_1  | Starting mock IAM (http port 4593)...
localstack_1  | Starting mock API Gateway (http port 4567)...
localstack_1  | Starting mock DynamoDB (http port 4569)...
localstack_1  | Starting mock Lambda service (http port 4574)...
localstack_1  | Starting mock CloudFormation (http port 4581)...
localstack_1  | Starting mock CloudWatch Logs (http port 4586)...
localstack_1  | Initializing DynamoDB Local with the following configuration:
localstack_1  | Port:	4564
localstack_1  | InMemory:	true
localstack_1  | DbPath:	null
localstack_1  | SharedDb:	true
localstack_1  | shouldDelayTransientStatuses:	false
localstack_1  | CorsParams:	*
localstack_1  | 
localstack_1  | 2019-10-11 00:26:20,422:API: 127.0.0.1 - - [11/Oct/2019 00:26:20] "GET / HTTP/1.1" 200 -
localstack_1  | Ready.
```

Here are the logs from serverless deploy:
```
SLS_DEBUG=* serverless deploy
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Using serverless-localstack
Serverless: Load command deploy
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
 
 Serverless Warning --------------------------------------
 
  A valid environment variable to satisfy the declaration 'env:EXISTING_TOPIC_ARN' could not be found.
 
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 503 1.096s 3 retries] describeStacks({ StackName: 'aws-nodejs-dev' })
Serverless: Recoverable error occurred (Service Unavailable), sleeping for 5 seconds. Try 1 of 4
Serverless: [AWS cloudformation 503 0.784s 3 retries] describeStacks({ StackName: 'aws-nodejs-dev' })
Serverless: Recoverable error occurred (Service Unavailable), sleeping for 5 seconds. Try 2 of 4
Serverless: [AWS cloudformation 503 0.721s 3 retries] describeStacks({ StackName: 'aws-nodejs-dev' })
Serverless: Recoverable error occurred (Service Unavailable), sleeping for 5 seconds. Try 3 of 4
Serverless: [AWS cloudformation 503 0.654s 3 retries] describeStacks({ StackName: 'aws-nodejs-dev' })
Serverless: Recoverable error occurred (Service Unavailable), sleeping for 5 seconds. Try 4 of 4
Serverless: [AWS cloudformation 503 0.922s 3 retries] describeStacks({ StackName: 'aws-nodejs-dev' })
 
  Serverless Error ---------------------------------------
 
  ServerlessError: Service Unavailable
      at promise.catch.err (/usr/local/src/nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:317:27)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              8.10.0
     Framework Version:         1.54.0
     Plugin Version:            3.1.2
     SDK Version:               2.1.2
     Components Core Version:   1.1.1
     Components CLI Version:    1.2.3
```

Not sure why but serverless installation cannot communicate with docker container, even though awslocal  cli still works, and using the aws cli with the --endpoint overridew works too.

Do you know of any common  ubuntu settings that might make communications with localstack docker instance fail? Do I need to do anything different with docker networks?

**Comment by irishabh96** [comment]
@bunnyUFO I was facing similar issue and got to know serverless localstack accept default region us-east-1 

Update your dockerfile 

```version: "2.1"
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4597:4567-4597"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
Add this to your serverless.yml
```
plugins:
  - serverless-localstack
custom:
  localstack:
    stages:
      - local
      - dev
    debug: true
    host: http://localhost
    endpointFile: localstack-endpoints.json
```

then run ```sls deploy --stage local --region us-east-1```

**Comment by bunnyUFO** [comment]
@irishabh96 Thanks, I think I did specify the regions to match but I will make sure and try again. If I can't get us-west-2 then I will just try the default `us-east-1`.
