### ISSUE TITLE
Error deploying to localstack: InvalidBucketName

### ISSUE THREAD

**Issue by aprat84** [localstack/serverless-localstack#58]
I get this error, starting localstack with DEBUG=1, when I try to deploy a hello world test project (1 lambda and 1 API Gateway endpoint).

Seems like serverless framework or this plugin generates an invalid bucket name (contains uppercase letters)

```log
2019-11-27 15:11:39,901:API: 127.0.0.1 - - [27/Nov/2019 15:11:39] "GET /test-project-local-ServerlessDeploymentBucket-5M5NXDTVY08Z?location HTTP/1.1" 404 -
2019-11-27 15:11:39,916:API: 127.0.0.1 - - [27/Nov/2019 15:11:39] "HEAD /test-project-local-ServerlessDeploymentBucket-5M5NXDTVY08Z HTTP/1.1" 404 -
2019-11-27T15:11:39:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response from CloudFormation (400) POST /: b'<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Stack with id test-project-local does not exist</Message>\n  </Error>\n  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>\n</ErrorResponse>'
2019-11-27T15:11:39:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently updating stack resource test-project-local/ServerlessDeploymentBucket: None
2019-11-27T15:11:39:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource (update=False, exists=False, updateable=False): {'Type': 'AWS::S3::Bucket', 'Properties': {'BucketEncryption': {'ServerSideEncryptionConfiguration': [{'ServerSideEncryptionByDefault': {'SSEAlgorithm': 'AES256'}}]}, 'BucketName': 'test-project-local-ServerlessDeploymentBucket-5M5NXDTVY08Z'}}
2019-11-27T15:11:39:DEBUG:localstack.utils.cloudformation.template_deployer: Deploying resource type "S3::Bucket" id "ServerlessDeploymentBucket"
2019-11-27T15:11:39:DEBUG:localstack.utils.cloudformation.template_deployer: Request for creating resource type "S3::Bucket" in region eu-west-1: create_bucket {'Bucket': 'test-project-local-ServerlessDeploymentBucket-5M5NXDTVY08Z', 'ACL': 'public-read', 'CreateBucketConfiguration': {'LocationConstraint': 'eu-west-1'}}
2019-11-27 15:11:40,564:API: 127.0.0.1 - - [27/Nov/2019 15:11:40] "GET /test-project-local-ServerlessDeploymentBucket-MPGD7SKUJ7QN?location HTTP/1.1" 404 -
2019-11-27 15:11:40,576:API: 127.0.0.1 - - [27/Nov/2019 15:11:40] "HEAD /test-project-local-ServerlessDeploymentBucket-MPGD7SKUJ7QN HTTP/1.1" 404 -
2019-11-27 15:11:40,691:API: 127.0.0.1 - - [27/Nov/2019 15:11:40] "GET /test-project-local-ServerlessDeploymentBucket-3T2BTL9C5DMP?location HTTP/1.1" 404 -
2019-11-27 15:11:40,703:API: 127.0.0.1 - - [27/Nov/2019 15:11:40] "HEAD /test-project-local-ServerlessDeploymentBucket-3T2BTL9C5DMP HTTP/1.1" 404 -
2019-11-27T15:11:40:WARNING:localstack.utils.cloudformation.template_deployer: Error calling <bound method ClientCreator._create_api_method.<locals>._api_call of <botocore.client.S3 object at 0x7f8cd1aaa350>> with params: {'Bucket': 'test-project-local-ServerlessDeploymentBucket-5M5NXDTVY08Z', 'ACL': 'public-read', 'CreateBucketConfiguration': {'LocationConstraint': 'eu-west-1'}} for resource: {'Type': 'AWS::S3::Bucket', 'Properties': {'BucketEncryption': {'ServerSideEncryptionConfiguration': [{'ServerSideEncryptionByDefault': {'SSEAlgorithm': 'AES256'}}]}, 'BucketName': 'test-project-local-ServerlessDeploymentBucket-5M5NXDTVY08Z'}}
2019-11-27T15:11:40:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "ServerlessDeploymentBucket": An error occurred (InvalidBucketName) when calling the CreateBucket operation: The specified bucket is not valid. Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 173, in parse_and_create_resource
    return _parse_and_create_resource(logical_id, resource_json, resources_map, region_name)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 260, in _parse_and_create_resource
    result = deploy_func(logical_id, resource_wrapped, stack_name=stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 713, in deploy_resource
    result = deploy_resource_via_sdk_function(resource_id, resources, resource_type, func, stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 783, in deploy_resource_via_sdk_function
    raise e
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 780, in deploy_resource_via_sdk_function
    result = function(**params)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidBucketName) when calling the CreateBucket operation: The specified bucket is not valid.
```

**Comment by whummer** [comment]
Thanks for reporting @aprat84 . This should be fixed in https://github.com/localstack/localstack/pull/1810 - can you please give it a try with the latest version of the Docker image (`docker pull localstack/localstack`). Thanks

**Comment by aprat84** [comment]
Thanks for quick reply @whummer. Error is indeed fixed after pulling latest docker image.
