### ISSUE TITLE
An error occurred (404) when calling the HeadObject operation: Not Found Traceback

### ISSUE THREAD

**Issue by nguyenhoai890** [localstack/serverless-localstack#64]
Dear team, 

I have a problem with the command:
`SLS_DEBUG=true serverless deploy --stage=local`

Could you please help me on trouble shooting it? 

The local stack logs is:
```
2019-12-26T05:01:08:WARNING:moto: No Moto CloudFormation support for AWS::S3::BucketPolicy
2019-12-26T05:01:13:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:publicspam-local-world
2019-12-26T05:01:14:INFO:localstack.services.cloudformation.cloudformation_starter: Updating resource ID from b01a26e9 to ggoazjguas (us-east-1)
2019-12-26T05:01:14:WARNING:localstack.services.cloudformation.cloudformation_starter: Unable to determine physical_resource_id for resource <class 'moto.apigateway.models.RestAPI'>
2019-12-26T05:01:15:INFO:localstack.services.cloudformation.cloudformation_starter: Updating resource ID from f4419f33 to 9cfmluuypy (us-east-1)
2019-12-26T05:01:15:WARNING:localstack.services.cloudformation.cloudformation_starter: Unable to determine physical_resource_id for resource <class 'moto.apigateway.models.Resource'>
2019-12-26T05:01:15:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:publicspam-local-world
2019-12-26T05:01:15:ERROR:localstack.services.generic_proxy: Error forwarding request: An error occurred (404) when calling the HeadObject operation: Not Found Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 297, in forward
    updated_response = self.proxy.update_listener.return_response(**kwargs)
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 938, in return_response
    fix_range_content_type(bucket_name, path, headers, response)
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 364, in fix_range_content_type
    result = s3_client.head_object(Bucket=bucket_name, Key=key_name)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 276, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 586, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
```

SLS logs:
```
Serverless: [AWS cloudformation 200 0.073s 0 retries] createStack({
  StackName: 'publicspam-local',
  OnFailure: 'DELETE',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateBody: '{"AWSTemplateFormatVersion":"2010-09-09","Description":"The AWS CloudFormation template for this Serverless application","Resources":{"ServerlessDeploymentBucket":{"Type":"AWS::S3::Bucket","Properties":{"BucketEncryption":{"ServerSideEncryptionConfiguration":[{"ServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}}},"ServerlessDeploymentBucketPolicy":{"Type":"AWS::S3::BucketPolicy","Properties":{"Bucket":{"Ref":"ServerlessDeploymentBucket"},"PolicyDocument":{"Statement":[{"Action":"s3:*","Effect":"Deny","Principal":"*","Resource":[{"Fn::Join":["",["arn:",{"Ref":"AWS::Partition"},":s3:::",{"Ref":"ServerlessDeploymentBucket"},"/*"]]}],"Condition":{"Bool":{"aws:SecureTransport":false}}}]}}}},"Outputs":{"ServerlessDeploymentBucketName":{"Value":{"Ref":"ServerlessDeploymentBucket"}}}}',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ]
})
Serverless: Checking Stack create progress...
Serverless: [AWS cloudformation 200 0.037s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:000000000000:stack/publicspam-local/315372bf-461b-46e1-a3ea-fe534391b067'
})
.
Serverless: Stack create finished...
Serverless: [AWS cloudformation 200 0.017s 0 retries] describeStackResource({
  StackName: 'publicspam-local',
  LogicalResourceId: 'ServerlessDeploymentBucket'
})
Serverless: [AWS s3 200 0.028s 0 retries] listObjectsV2({
  Bucket: 'publicspam-local-ServerlessDeploymentBucket-SCCIDTGR4VAE',
  Prefix: 'serverless/publicspam/local'
})
Serverless: [AWS lambda 404 0.008s 0 retries] getFunction({ FunctionName: 'publicspam-local-world' })
Serverless: [AWS sts 200 0.014s 0 retries] getCallerIdentity({})
Serverless: Uploading CloudFormation file to S3...
Serverless: [AWS s3 200 0.019s 0 retries] putObject({
  Body: <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... 4187 more bytes>,
  Bucket: 'publicspam-local-ServerlessDeploymentBucket-SCCIDTGR4VAE',
  Key: 'serverless/publicspam/local/1577336468236-2019-12-26T05:01:08.236Z/compiled-cloudformation-template.json',
  ContentType: 'application/json',
  Metadata: { filesha256: 'ctCUczkUhYEWjH7txOH75N0067Kk4iV4f0bX1bA9jo4=' }
})
Serverless: Uploading artifacts...
Serverless: Uploading service publicspam.zip file to S3 (25.81 MB)...
Serverless: [AWS s3 200 0.073s 0 retries] createMultipartUpload({
  Bucket: 'publicspam-local-ServerlessDeploymentBucket-SCCIDTGR4VAE',
  Key: 'serverless/publicspam/local/1577336468236-2019-12-26T05:01:08.236Z/publicspam.zip',
  ContentType: 'application/zip',
  Metadata: { filesha256: 'wLZIXlm3C/3lpzoLs+vskeWi4mzEsDc2Q/chtBn/uG8=' }
})
Serverless: [AWS s3 200 0.266s 0 retries] uploadPart({
  Body: <Buffer db aa c7 19 64 0a bd 5e a1 e3 07 53 0f 37 ae 87 26 72 6e 4a 85 1a 37 38 a7 c8 78 ad 1a 81 7b 55 18 d9 e9 f8 d0 81 31 52 37 80 f3 89 64 31 13 8c ab 76 ... 5242830 more bytes>,
  ContentLength: 5242880,
  PartNumber: 2,
  Bucket: 'publicspam-local-ServerlessDeploymentBucket-SCCIDTGR4VAE',
  Key: 'serverless/publicspam/local/1577336468236-2019-12-26T05:01:08.236Z/publicspam.zip',
  UploadId: 'FKkFzf9pKRRwlBLvhWfuy5lXGgA0rheeFS3Q9yp8iZjBeDmDSM7ZLfubvw'
})
Serverless: [AWS s3 200 0.32s 0 retries] uploadPart({
  Body: <Buffer 50 4b 03 04 14 00 08 00 08 00 00 00 21 00 00 00 00 00 00 00 00 00 00 00 00 00 0f 00 00 00 62 69 6e 2f 63 6f 6e 66 69 67 2e 6a 73 6f 6e 95 d0 b1 0a 83 ... 5242830 more bytes>,
  ContentLength: 5242880,
  PartNumber: 1,
  Bucket: 'publicspam-local-ServerlessDeploymentBucket-SCCIDTGR4VAE',
  Key: 'serverless/publicspam/local/1577336468236-2019-12-26T05:01:08.236Z/publicspam.zip',
  UploadId: 'FKkFzf9pKRRwlBLvhWfuy5lXGgA0rheeFS3Q9yp8iZjBeDmDSM7ZLfubvw'
})
Serverless: [AWS s3 200 0.293s 0 retries] uploadPart({
  Body: <Buffer bc cf 81 77 34 cb c2 22 d4 f6 56 11 46 4e e5 6e f7 8e 0f 36 d2 32 c4 b8 d4 5f 98 c0 49 53 09 45 8b 1c 84 eb fa 29 81 f3 85 40 ea ff 83 00 97 fa 81 09 ... 5242830 more bytes>,
  ContentLength: 5242880,
  PartNumber: 3,
  Bucket: 'publicspam-local-ServerlessDeploymentBucket-SCCIDTGR4VAE',
  Key: 'serverless/publicspam/local/1577336468236-2019-12-26T05:01:08.236Z/publicspam.zip',
  UploadId: 'FKkFzf9pKRRwlBLvhWfuy5lXGgA0rheeFS3Q9yp8iZjBeDmDSM7ZLfubvw'
})
Serverless: [AWS s3 200 0.073s 0 retries] uploadPart({
  Body: <Buffer 12 f0 69 32 fd b5 5a 6b 20 48 a0 6e 66 8d 89 44 92 25 f0 0e 21 8f c1 6a cd e4 91 8d e8 84 72 0b 42 5a 4a 37 75 5c 31 ba c4 42 f4 d4 76 f0 77 79 e7 a8 ... 852109 more bytes>,
  ContentLength: 852159,
  PartNumber: 6,
  Bucket: 'publicspam-local-ServerlessDeploymentBucket-SCCIDTGR4VAE',
  Key: 'serverless/publicspam/local/1577336468236-2019-12-26T05:01:08.236Z/publicspam.zip',
  UploadId: 'FKkFzf9pKRRwlBLvhWfuy5lXGgA0rheeFS3Q9yp8iZjBeDmDSM7ZLfubvw'
})
Serverless: [AWS s3 200 0.217s 0 retries] uploadPart({
  Body: <Buffer 7d d8 80 fb 6d 97 55 61 99 48 45 54 f1 6a 13 f0 58 20 5c 87 79 b3 db 1d 2e 45 d9 ad f9 15 85 bb 4c 85 64 45 c7 c2 57 12 50 95 7b 0e f3 f0 1b 13 9c a7 ... 5242830 more bytes>,
  ContentLength: 5242880,
  PartNumber: 5,
  Bucket: 'publicspam-local-ServerlessDeploymentBucket-SCCIDTGR4VAE',
  Key: 'serverless/publicspam/local/1577336468236-2019-12-26T05:01:08.236Z/publicspam.zip',
  UploadId: 'FKkFzf9pKRRwlBLvhWfuy5lXGgA0rheeFS3Q9yp8iZjBeDmDSM7ZLfubvw'
})
Serverless: [AWS s3 200 0.247s 0 retries] uploadPart({
  Body: <Buffer da bc c0 c7 a1 29 a0 3c 15 b0 74 3f e8 0e 59 54 da e5 d2 fe 93 27 80 3f a5 1d 11 d7 82 39 15 bf 63 34 81 47 3a 78 2b 3f e7 b8 62 c1 e5 d7 8e 1c 75 e9 ... 5242830 more bytes>,
  ContentLength: 5242880,
  PartNumber: 4,
  Bucket: 'publicspam-local-ServerlessDeploymentBucket-SCCIDTGR4VAE',
  Key: 'serverless/publicspam/local/1577336468236-2019-12-26T05:01:08.236Z/publicspam.zip',
  UploadId: 'FKkFzf9pKRRwlBLvhWfuy5lXGgA0rheeFS3Q9yp8iZjBeDmDSM7ZLfubvw'
})
Serverless: [AWS s3 200 0.085s 0 retries] completeMultipartUpload({
  MultipartUpload: {
    Parts: [
      { ETag: '"b5fb0acdc40a40fb6c479aa183c05cd9"', PartNumber: 1 },
      { ETag: '"e9e6f992a89f5adbadacd9286edaf5fa"', PartNumber: 2 },
      { ETag: '"244ea399d842f18b69f46a6b1ef598d1"', PartNumber: 3 },
      { ETag: '"1100aa4328c3b1e693a8a633f151023b"', PartNumber: 4 },
      { ETag: '"cc841bfff02a9fdc90fd9af42d237555"', PartNumber: 5 },
      { ETag: '"fad837830b7a19e3ee602b18be1507a7"', PartNumber: 6 },
      [length]: 6
    ]
  },
  Bucket: 'publicspam-local-ServerlessDeploymentBucket-SCCIDTGR4VAE',
  Key: 'serverless/publicspam/local/1577336468236-2019-12-26T05:01:08.236Z/publicspam.zip',
  UploadId: 'FKkFzf9pKRRwlBLvhWfuy5lXGgA0rheeFS3Q9yp8iZjBeDmDSM7ZLfubvw'
})
Serverless: Validating template...
Serverless: Skipping template validation: Unsupported in Localstack
Serverless: Updating Stack...
Serverless: [AWS cloudformation 400 14.223s 0 retries] updateStack({
  StackName: 'publicspam-local',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: 'https://s3.amazonaws.com/publicspam-local-ServerlessDeploymentBucket-SCCIDTGR4VAE/serverless/publicspam/local/1577336468236-2019-12-26T05:01:08.236Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ]
})
 
  Serverless Error ---------------------------------------
 
  ServerlessError: Bad Request
      at /usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:317:27
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

My Environment information:
```
     Operating System:          darwin
     Node Version:              12.13.1
     Framework Version:         1.58.0
     Plugin Version:            3.2.5
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```

serverless-localstack: "^0.4.22"

I'm using localstack/localstack@latest

Thanks,

**Comment by whummer** [comment]
Thanks for reporting @nguyenhoai890 . This should be fixed in https://github.com/localstack/localstack/pull/1906 - can you please give it a try with the latest version of the Docker image? Thanks

**Comment by gcampionpae** [comment]
I'm also having the same issue.  I pulled the most recent version of the localstack repo today and used docker-compose up to run local stack and it still is throwing the same error.

Command:
```
SLS_DEBUG=* sls deploy -s local --profile local
```
Serverless output:
```
Serverless: [AWS cloudformation 400 0.041s 0 retries] updateStack({ StackName: 'sls-accounts-local',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL:
   'http://192.168.5.241:4572/sls-accounts-local-ServerlessDeploymentBucket-MTQRDW7DTVWH/serverless/sls-accounts/local/1578414272440-2020-01-07T16:24:32.440Z/compiled-cloudformation-template.json',
  Tags:
   [ { Key: 'STAGE', Value: 'local' },
     { Key: 'git-commit', Value: 'master - 0f66872' },
     [length]: 2 ] })

  Serverless Error ---------------------------------------

  ServerlessError: Bad Request
      at promise.catch.err (/sls_plugins/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:326:27)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```
Localstack output: 
```
localstack_main | 2020-01-07T16:24:33:WARNING:moto: No Moto CloudFormation support for AWS::S3::BucketPolicy
localstack_main | 2020-01-07T16:24:38:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:sls-accounts-local-fetchBillingDetails
localstack_main | 2020-01-07T16:24:38:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:sls-accounts-local-fetchCard
localstack_main | 2020-01-07T16:24:38:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:sls-accounts-local-listInvoices
localstack_main | 2020-01-07T16:24:38:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:sls-accounts-local-updateBillingDetails
localstack_main | 2020-01-07T16:24:38:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:sls-accounts-local-fetchInvoice
localstack_main | 2020-01-07T16:24:38:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:sls-accounts-local-updateCustomerName
localstack_main | 2020-01-07T16:24:38:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:sls-accounts-local-createCustomer
localstack_main | 2020-01-07T16:24:38:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:sls-accounts-local-publishEventCustomerLoggedIn
```

**Comment by SpicySyntax** [comment]
+1 for this issue

**Comment by whummer** [comment]
Thanks for the update @gcampionpae @SpicySyntax . Not sure if the error you're seeing is the _exact_ same issue as the one originally reported.

Can you please open a new ticket with a small, self-contained example that helps reproduce your error? Please also post the full error logs with `DEBUG=1` enabled in the LocalStack process. Thanks!

**Comment by greenreign** [comment]
@whummer Here is a gist where I get the same behavior.  I think this is the most basic example you could have of trying to configure serverless with localstack and it does not work for me in Windows 10

https://gist.github.com/greenreign/cb7839ca24e91d3aab1297ef0412d18f

**Comment by gcampionpae** [comment]
@greenreign thanks for posting that, I wanted to try and replicate it but haven't had the time!

**Comment by phenom5886** [comment]
I am also experiencing this behaviour with the latest localstack/localstack Docker image.

Environment Information:
     Operating System:          darwin
     Node Version:              12.13.1
     Framework Version:         1.66.0 (standalone)
     Plugin Version:            3.4.1
     SDK Version:               2.3.0
     Components Version:        2.22.3

**Comment by rsosnin** [comment]
While using localstack:0.10.8 , I'm also getting the error when trying to put object in the local s3 bucket.
More details:
```
2020-03-22T11:21:47:ERROR:localstack.services.generic_proxy: Error forwarding request: An error occurred (404) when calling the HeadObject operation: Not Found Traceback (most recent call last):
localstack               |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 303, in forward
localstack               |     updated_response = self.proxy.update_listener.return_response(**kwargs)
localstack               |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1000, in return_response
localstack               |     fix_range_content_type(bucket_name, path, headers, response)
localstack               |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 380, in fix_range_content_type
localstack               |     result = s3_client.head_object(Bucket=bucket_name, Key=key_name)
localstack               |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
localstack               |     return self._make_api_call(operation_name, kwargs)
localstack               |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 626, in _make_api_call
localstack               |     raise error_class(parsed_response, operation_name)
localstack               | botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
```

my code snippet:
```
file_to_upload = open(file_path, 'rb')
response = s3_client.put_object(
        ACL='public-read-write',
        Body=file_to_upload,
        Bucket=function_s3_bucket,
        Key=function_s3_key
    )
```
