### ISSUE TITLE
AttributeError: 'Rule' object has no attribute 'get_cfn_attribute'

### ISSUE THREAD

**Issue by ghost** [localstack/serverless-localstack#85]
When trying to deploy a scheduled Lambda function (triggered using CloudWatch Events/EventBridge) I get the following error:

```
e2e___localstack_1 | 2020-04-07T09:45:41:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "TrackEventsLambdaPermissionEventsRuleSchedule1": 'Rule' object has no attribute 'get_cfn_attribute' Traceback (most recent call last):
e2e___localstack_1 |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 175, in parse_and_create_resource
e2e___localstack_1 |     return _parse_and_create_resource(
e2e___localstack_1 |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 203, in _parse_and_create_resource
e2e___localstack_1 |     resource_tuple = parsing.parse_resource(logical_id, resource_json, resources_map)
e2e___localstack_1 |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 314, in parse_resource
e2e___localstack_1 |     resource_json = clean_json(resource_json, resources_map)
e2e___localstack_1 |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 159, in clean_json
e2e___localstack_1 |     result = clean_json_orig(resource_json, resources_map)
e2e___localstack_1 |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 259, in clean_json
e2e___localstack_1 |     cleaned_val = clean_json(value, resources_map)
e2e___localstack_1 |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 159, in clean_json
e2e___localstack_1 |     result = clean_json_orig(resource_json, resources_map)
e2e___localstack_1 |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 259, in clean_json
e2e___localstack_1 |     cleaned_val = clean_json(value, resources_map)
e2e___localstack_1 |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 159, in clean_json
e2e___localstack_1 |     result = clean_json_orig(resource_json, resources_map)
e2e___localstack_1 |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 174, in clean_json
e2e___localstack_1 |     return resource.get_cfn_attribute(resource_json["Fn::GetAtt"][1])
e2e___localstack_1 | AttributeError: 'Rule' object has no attribute 'get_cfn_attribute'
```

I believe the issue is similar to https://github.com/localstack/serverless-localstack/issues/60 and https://github.com/localstack/localstack/issues/2000

Using `localstack:0.11.0` (also tried `latest`) and the following environment:

```
     Operating System:          darwin
     Node Version:              12.13.1
     Framework Version:         1.66.0 (standalone)
     Plugin Version:            3.4.1
     SDK Version:               2.3.0
     Components Version:        2.22.3
```

**Comment by oguzhancagliyan** [comment]
Same. Find any solution?

**Comment by whummer** [comment]
Hi @oguzhancagliyan @ghost - can you please do a `docker pull localstack/localstack` and give it a try with the `latest` version of the Docker image? If the problem persits, can you please provide a minimal example to help reproduce this issue? Thanks for your help.
