### ISSUE TITLE
'uname' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by talaikis** [localstack/serverless-localstack#97]
serverless deploy -s local:

```bash
Serverless: Using serverless-localstack
Serverless: Starting LocalStack in Docker. This can take a while.

  Error --------------------------------------------------

  Error: Command failed: localstack infra start --docker
  'uname' is not recognized as an internal or external command,
  operable program or batch file.
  2020-07-22T14:28:08:DEBUG:bootstrap.py: Unable to load plugins from module C:\Python38\lib\site-packages\localstack_ext\plugins.py: invalid syntax (<string>, line 1)
  2020-07-22T14:28:08:DEBUG:bootstrap.py: Unable to load plugins from module C:\Python38\lib\site-packages\localstack\plugins.py: invalid syntax (<string>, line 1)
  2020-07-22T14:28:08:DEBUG:bootstrap.py: Unable to load plugins from module C:\Python38\lib\site-packages\localstack_ext\plugins.py: invalid syntax (<string>, line 1)
  2020-07-22T14:28:08:DEBUG:bootstrap.py: Unable to load plugins from module C:\Python38\lib\site-packages\localstack\plugins.py: invalid syntax (<string>, line 1)
  'uname' is not recognized as an internal or external command,
  operable program or batch file.
  'uname' is not recognized as an internal or external command,
  operable program or batch file.

      at ChildProcess.exithandler (child_process.js:303:12)
      at ChildProcess.emit (events.js:315:20)
      at ChildProcess.EventEmitter.emit (domain.js:482:12)
      at maybeClose (internal/child_process.js:1021:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

Environment:

```bash
Operating System:          win32
     Node Version:              12.18.2
     Framework Version:         1.75.1
     Plugin Version:            3.6.16
     SDK Version:               2.3.1
     Components Version:        2.32.0
```

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-29) by [Unito](https://www.unito.io/learn-more)

**Comment by drewsb** [comment]
Experiencing the same issue. Any update on this?

**Comment by whummer** [comment]
Thanks for reporting @talaikis @drewsb . This should be (hopefully) fixed in the meantime - can you please give it another try with the latest version of the Serverless plugin and the LocalStack Docker image:
```
docker pull localstack/localstack
```
and
```
pip install --upgrade localstack
```

Hope that helps - please keep us posted. Thanks

**Comment by BartusZak** [comment]
`C:\Users\bploszynski>localstack start

C:\Users\bploszynski>python C:\Python38\Scripts\\localstack start
'uname' is not recognized as an internal or external command,
operable program or batch file.
LocalStack version: 0.12.1
Starting local dev environment. CTRL-C to quit.
ERROR: 'chmod -R 777 "C:\Users\BPLOSZ~1\AppData\Local\Temp\localstack"': exit code 1; output: b"'chmod' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
docker run -it -e LOCALSTACK_HOSTNAME="localhost" -e DEFAULT_REGION="us-east-1" -e TEST_AWS_ACCOUNT_ID="000000000000" --rm --privileged --name localstack_main -p 4566:4566 -p 4571:4571 -p 8080-8081:8080-8081  -v "C:\Users\BPLOSZ~1\AppData\Local\Temp\localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="C:\Users\BPLOSZ~1\AppData\Local\Temp\localstack" "localstack/localstack"
'uname' is not recognized as an internal or external command,
operable program or batch file.
'uname' is not recognized as an internal or external command,
operable program or batch file.
Waiting for all LocalStack services to be ready
2020-11-03 10:54:51,321 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-11-03 10:54:51,325 INFO supervisord started with pid 13
2020-11-03 10:54:52,328 INFO spawned: 'dashboard' with pid 19
2020-11-03 10:54:52,330 INFO spawned: 'infra' with pid 20
2020-11-03 10:54:52,334 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2020-11-03 10:54:52,335 INFO exited: dashboard (exit status 0; expected)
(. .venv/bin/activate; exec bin/localstack start --host)
LocalStack version: 0.12.1
Starting local dev environment. CTRL-C to quit.
2020-11-03 10:54:53,707 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Starting edge router (https port 4566)...
Starting mock ACM service on http port 4566 ...
2020-11-03T10:54:56:INFO:localstack.utils.analytics.profiler: Execution of "load_plugin_from_path" took 3207.2088718414307ms
2020-11-03T10:54:56:INFO:localstack.utils.analytics.profiler: Execution of "load_plugins" took 3207.476854324341ms
2020-11-03T10:54:56:INFO:localstack.multiserver: Starting multi API server process on port 44083
[2020-11-03 10:54:56 +0000] [21] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2020-11-03T10:54:56:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
[2020-11-03 10:54:56 +0000] [21] [INFO] Running on http://0.0.0.0:44083 (CTRL + C to quit)
2020-11-03T10:54:56:INFO:hypercorn.error: Running on http://0.0.0.0:44083 (CTRL + C to quit)
Starting mock API Gateway service on http port 4566 ...
Starting mock CloudFormation service on http port 4566 ...
Starting mock CloudWatch service on http port 4566 ...
Starting mock DynamoDB service on http port 4566 ...
Starting mock DynamoDB Streams service on http port 4566 ...
Starting mock EC2 service on http port 4566 ...
Starting mock ES service on http port 4566 ...
Starting mock Firehose service on http port 4566 ...
Starting mock IAM service on http port 4566 ...
Starting mock STS service on http port 4566 ...
Starting mock Kinesis service on http port 4566 ...
Starting mock KMS service on http port 4566 ...
Waiting for all LocalStack services to be ready
Starting mock Lambda service on http port 4566 ...
Starting mock CloudWatch Logs service on http port 4566 ...
Starting mock Redshift service on http port 4566 ...
Starting mock Route53 service on http port 4566 ...
Starting mock S3 service on http port 4566 ...
Starting mock Secrets Manager service on http port 4566 ...
Starting mock SES service on http port 4566 ...
Starting mock SNS service on http port 4566 ...
Starting mock SQS service on http port 4566 ...
Starting mock SSM service on http port 4566 ...
Starting mock Cloudwatch Events service on http port 4566 ...
Starting mock StepFunctions service on http port 4566 ...
Waiting for all LocalStack services to be ready
Ready.
2020-11-03T10:55:06:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 10673.666000366211ms

**Comment by steffyP** [comment]
The issue should have been fixed in the meantime. Please let us know if you still encounter any issues.
