### ISSUE TITLE
Integer statusCode for ApiGateway::Method Response throws ParamValidationError on deploy

### ISSUE THREAD

**Issue by Undre4m** [localstack/serverless-localstack#98]
### Description
Parameter validation error when trying to create API Gateway resources breaks deployment.

> Unable to parse and create resource "ApiGatewayMethodSlackGet": Parameter validation failed:
> Invalid type for parameter ***statusCode***, value: 201, type: **<class 'int'>**, valid types: **<class 'str'>**

An [issue](https://github.com/serverless/serverless/issues/7970) has been opened at [serverless/serverless](https://github.com/serverless/serverless) for generating AWS compliant cloudformation templates, but the stack should be made more lenient in order to more closely resemble AWS services.  

#### Triggering CFT block:
```jsonb
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Resources": {
        "ApiGatewayMethodExamplePost": {
            "Type": "AWS::ApiGateway::Method",
            "Properties": {
                "HttpMethod": "POST",
                "MethodResponses": [{
                    "ResponseParameters": {},
                    "ResponseModels": {},
                    "StatusCode": 200
                }
        ...
        "ApiGatewayMethodExampleGet": {
            "Type": "AWS::ApiGateway::Method",
            "Properties": {
                "HttpMethod": "GET",
                "MethodResponses": [{
                    "ResponseParameters": {},
                    "ResponseModels": {},
                    "StatusCode": 201
                }
        ...
}
```

AWS docs for [AWS::ApiGateway::Method MethodResponse](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apitgateway-method-methodresponse.html) objects

#### serverless.yml
```yaml
service: example

plugins:
  - serverless-localstack
  - serverless-webpack

custom:
  stage: ${opt:stage, self:provider.defaultStage}
  localstack:
    stages:
      - local
    host: http://localhost
    autostart: true
    debug: true

provider:
  name: aws
  runtime: nodejs12.x
  defaultStage: development

functions:
  slack:
    handler: src/index.handler
    events:
      - http:
          path: v1
          method: post
          integration: lambda
          response:
            template: $input.path('$')
            statusCodes:
              200:
                pattern: ''
              400:
                pattern: '.*"customLambdaError".*'
                template: $input.path('$.errorMessage')
              409:
                pattern: '.*"statusCode":409,.*'
                template:
                  application/json: $input.path("$.errorMessage")
                  application/xml: $input.path("$.body.errorMessage")
                headers:
                  Content-Type: "'application/json+hal'"

      - http:
          path: v1
          method: get
          integration: lambda
          request:
            parameters:
              querystrings:
                code: true
                state: true
          response:
            statusCodes:
              201:
                pattern: ''
              302:
                pattern: http.*
                headers:
                  Location: integration.response.body.errorMessage
                  Cache-Control: "'no-cache, no-store, must-revalidate'"

```

#### Logs
```bash
Waiting for all LocalStack services to be ready
2020-07-22 19:25:49,148 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-07-22 19:25:49,154 INFO supervisord started with pid 13
2020-07-22 19:25:50,158 INFO spawned: 'dashboard' with pid 19
2020-07-22 19:25:50,161 INFO spawned: 'infra' with pid 20
2020-07-22 19:25:50,172 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2020-07-22 19:25:50,173 INFO exited: dashboard (exit status 0; expected)
(. .venv/bin/activate; exec bin/localstack start --host)
LocalStack version: 0.11.3
Starting local dev environment. CTRL-C to quit.
2020-07-22 19:25:51,844 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Waiting for all LocalStack services to be ready
Starting edge router (https port 4566)...
Starting mock API Gateway service on http ports 4566 (recommended) and 4567 (deprecated)...
2020-07-22T19:25:57:INFO:localstack.multiserver: Starting multi API server process on port 37693
Running on 0.0.0.0:37693 over http (CTRL + C to quit)
Running on 0.0.0.0:4567 over http (CTRL + C to quit)
Running on 0.0.0.0:4566 over https (CTRL + C to quit)
Starting mock CloudFormation service in http ports 4566 (recommended) and 4581 (deprecated)...
Starting mock CloudWatch service on http ports 4566 (recommended) and 4582 (deprecated)...
Starting mock DynamoDB service in http ports 4566 (recommended) and 4569 (deprecated)...
Starting mock DynamoDB Streams service on http ports 4566 (recommended) and 4570 (deprecated)...
Starting mock EC2 service on http ports 4566 (recommended) and 4597 (deprecated)...
Starting mock ES service on http ports 4566 (recommended) and 4578 (deprecated)...
Starting mock Firehose service on http ports 4566 (recommended) and 4573 (deprecated)...
Starting mock IAM service on http ports 4566 (recommended) and 4593 (deprecated)...
Running on 0.0.0.0:4581 over http (CTRL + C to quit)
Running on 0.0.0.0:4569 over http (CTRL + C to quit)
Starting mock STS service on http ports 4566 (recommended) and 4592 (deprecated)...
Starting mock Kinesis service in http ports 4566 (recommended) and 4568 (deprecated)...
Starting mock KMS service in http ports 4566 (recommended) and 4599 (deprecated)...
Starting mock Lambda service on http ports 4566 (recommended) and 4574 (deprecated)...
Starting mock CloudWatch Logs service on http ports 4566 (recommended) and 4586 (deprecated)...
Starting mock Redshift service on http ports 4566 (recommended) and 4577 (deprecated)...
Starting mock Route53 service on http ports 4566 (recommended) and 4580 (deprecated)...
Starting mock S3 service on http ports 4566 (recommended) and 4572 (deprecated)...
Starting mock Secrets Manager service on http ports 4566 (recommended) and 4584 (deprecated)...
Starting mock SES service on http ports 4566 (recommended) and 4579 (deprecated)...
Starting mock SNS service on http ports 4566 (recommended) and 4575 (deprecated)...
Starting mock SQS service on http ports 4566 (recommended) and 4576 (deprecated)...
Starting mock SSM service on http ports 4566 (recommended) and 4583 (deprecated)...
Starting mock Cloudwatch Events service on http ports 4566 (recommended) and 4587 (deprecated)...
Starting mock StepFunctions service in http ports 4566 (recommended) and 4585 (deprecated)...
Running on 0.0.0.0:4593 over http (CTRL + C to quit)
Running on 0.0.0.0:4568 over http (CTRL + C to quit)
Running on 0.0.0.0:4599 over http (CTRL + C to quit)
Running on 0.0.0.0:4586 over http (CTRL + C to quit)
Running on 0.0.0.0:4572 over http (CTRL + C to quit)
Running on 0.0.0.0:4584 over http (CTRL + C to quit)
Running on 0.0.0.0:4575 over http (CTRL + C to quit)
Running on 0.0.0.0:4576 over http (CTRL + C to quit)
Running on 0.0.0.0:4583 over http (CTRL + C to quit)
Running on 0.0.0.0:4587 over http (CTRL + C to quit)
Running on 0.0.0.0:4585 over http (CTRL + C to quit)
Waiting for all LocalStack services to be ready
Ready.
2020-07-22T19:26:15:WARNING:localstack.services.cloudformation.cloudformation_starter: Unable to determine physical_resource_id for resource <class 'localstack.services.cloudformation.service_models.S3BucketPolicy'>
2020-07-22T19:26:20:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:example-local-slack
2020-07-22T19:26:21:INFO:localstack.services.cloudformation.cloudformation_starter: Updating resource ID from 8ed3f4ca to ub3pfdob3t (us-east-1)
2020-07-22T19:26:21:WARNING:localstack.services.cloudformation.cloudformation_starter: Unable to determine physical_resource_id for resource <class 'moto.apigateway.models.RestAPI'>
2020-07-22T19:26:21:INFO:localstack.services.cloudformation.cloudformation_starter: Updating resource ID from 932ac262 to urdlba0vgj (us-east-1)
2020-07-22T19:26:21:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:example-local-slack
2020-07-22T19:26:21:WARNING:localstack.services.cloudformation.cloudformation_starter: Unable to determine physical_resource_id for resource <class 'moto.apigateway.models.Resource'>
2020-07-22T19:26:22:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "ApiGatewayMethodV1Get": Parameter validation failed:
Invalid type for parameter statusCode, value: 201, type: <class 'int'>, valid types: <class 'str'> Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 221, in parse_and_create_resource
    return _parse_and_create_resource(
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 350, in _parse_and_create_resource
    result = deploy_func(logical_id, resource_map_new, stack_name=stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1076, in deploy_resource
    return execute_resource_action(resource_id, resources, stack_name, ACTION_CREATE)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1106, in execute_resource_action
    result = configure_resource_via_sdk(resource_id, resources, resource_type, func, stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1204, in configure_resource_via_sdk
    apigateway.put_method_response(restApiId=api_id, resourceId=res_id,
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 607, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 655, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter statusCode, value: 201, type: <class 'int'>, valid types: <class 'str'>

2020-07-22T19:26:27:WARNING:localstack.services.cloudformation.cloudformation_starter: Unable to resolve "Ref" attribute for: {'Ref': 'SlackLambdaVersionZ8JtoHiw2s84w2ZI7qlEbMZRBJE2ypijsNTvHx2P32M'} - SlackLambdaVersionZ8JtoHiw2s84w2ZI7qlEbMZRBJE2ypijsNTvHx2P32M - <class 'moto.awslambda.models.LambdaVersion'>
2020-07-22T19:26:27:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "ApiGatewayMethodV1Post": Parameter validation failed:
Invalid type for parameter statusCode, value: 200, type: <class 'int'>, valid types: <class 'str'> Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 221, in parse_and_create_resource
    return _parse_and_create_resource(
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 350, in _parse_and_create_resource
    result = deploy_func(logical_id, resource_map_new, stack_name=stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1076, in deploy_resource
    return execute_resource_action(resource_id, resources, stack_name, ACTION_CREATE)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1106, in execute_resource_action
    result = configure_resource_via_sdk(resource_id, resources, resource_type, func, stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1204, in configure_resource_via_sdk
    apigateway.put_method_response(restApiId=api_id, resourceId=res_id,
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 607, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 655, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter statusCode, value: 200, type: <class 'int'>, valid types: <class 'str'>

2020-07-22T19:26:28:INFO:localstack.services.cloudformation.cloudformation_starter: Updating resource ID from 7e47dc22 to 3g0vqltcw8 (us-east-1)
2020-07-22T19:26:28:WARNING:localstack.services.cloudformation.cloudformation_starter: Unable to determine physical_resource_id for resource <class 'moto.apigateway.models.Deployment'>
```

**Comment by whummer** [comment]
Thanks for reporting @Undre4m . This should be fixed in this commit: https://github.com/localstack/localstack/commit/cfcc30bcf560a738616d9a675f768534936b74b2 Can you please do a `docker pull localstack/localstack` and give it another try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks!
